import { PageHeader, SectionNav } from '../../components/common/page-header'
import { EmptyState } from '../../components/common/states'
import { scienceIndexes } from './public-repository'
import { scienceWords } from './catalogue'
import { parseScienceQuery, searchScience, type ScienceQuery } from './query'
export function ScienceGlossary({ query, onChange }: { query: ScienceQuery; onChange: (query: ScienceQuery) => void }) {
  const records = searchScience(query), ids = new Set(records.map((topic) => topic.id))
  const terms = scienceIndexes.glossary.filter((entry) => ids.has(entry.topic.id))
  const letters = [...new Set(terms.map((entry) => entry.term[0]?.toUpperCase() ?? '#'))]
  return <div className="page detail-page"><PageHeader title="Training glossary" description="Reviewed terminology, abbreviations and aliases linked to their canonical topic." /><SectionNav items={[{ label: 'Topics', href: '/learn/workout-science' }, { label: 'Methods', href: '/learn/workout-science/methods' }, { label: 'Glossary', href: '/learn/workout-science/glossary', active: true }]} /><label className="search-field"><input aria-label="Search training glossary" value={query.q} onChange={(event) => onChange({ ...query, q: event.target.value })} placeholder="Find a term or abbreviation…" /></label><label className="glossary-category">Glossary category<select value={query.category[0] ?? ''} onChange={(event) => onChange({ ...query, category: event.target.value ? [event.target.value] : [] })}><option value="">All categories</option>{[...new Set(scienceIndexes.published.map((topic) => topic.category))].map((id) => <option key={id} value={id}>{scienceWords(id)}</option>)}</select></label><SectionNav label="Glossary letters" items={letters.map((letter) => ({ label: letter, href: `#letter-${letter}` }))} /><p role="status">{terms.length} reviewed terms</p>{letters.map((letter) => <section key={letter} id={`letter-${letter}`} tabIndex={-1}><h2>{letter}</h2><dl>{terms.filter((entry) => entry.term[0]?.toUpperCase() === letter).map((entry) => <div className="glossary-term" key={`${entry.topic.id}-${entry.term}`}><dt><a href={`/learn/workout-science/${entry.topic.slug}`}>{entry.term}</a>{entry.term !== entry.topic.displayName && <span> — {entry.topic.displayName}</span>}</dt><dd>{entry.topic.definition}</dd></div>)}</dl></section>)}{!terms.length && <EmptyState title="No reviewed glossary terms match." description="Terms appear after their canonical topics pass evidence and editorial review."><button className="button secondary" onClick={() => onChange(parseScienceQuery({}))}>Clear glossary search</button></EmptyState>}</div>
}
