import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
test('anatomy selector, shared URL filters and public content gate', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/muscles')
  await expect(page.getByRole('heading', { name: 'Muscle library', exact: true })).toBeVisible()
  const region = page.getByRole('button', { name: 'Select Chest on body map' })
  await expect(region).toBeEnabled()
  await expect(page.getByRole('button', { name: 'Find a module' })).toBeEnabled()
  await region.focus()
  await page.keyboard.press('Space')
  await expect(page).toHaveURL(/region=region_chest/)
  await expect(page.locator('.region-text-list').getByRole('button', { name: 'Chest', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.reload()
  await expect(page.getByRole('button', { name: 'Select Chest on body map' })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Back', exact: true }).click()
  await page.getByRole('button', { name: 'Select Upper back on body map' }).click()
  await expect(page).toHaveURL(/region=region_upper_back/)
  await page.getByRole('button', { name: 'List', exact: true }).click()
  await expect(page.locator('.body-browser')).toHaveCount(0)
  await page.getByRole('textbox', { name: 'Search muscles' }).fill('lower abs')
  await expect(page).toHaveURL(/q=lower/)
  await page.getByRole('button', { name: 'Clear all filters' }).click()
  await page.getByRole('button', { name: 'Body', exact: true }).click()
  await page.getByRole('button', { name: 'Filters', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Filter the library' })
  await expect(dialog).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: 'Filters', exact: true })).toBeFocused()
  expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa']).analyze()).violations).toEqual([])
})
test('anatomy mobile, dark and missing entity are safe', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/muscles?region=made-up&type=fake&view=body')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await expect(page.locator('.region-text-list').getByRole('button')).toHaveCount(13)
  expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa']).analyze()).violations).toEqual([])
  await page.goto('/settings')
  await page.getByRole('radio', { name: 'Dark', exact: true }).check()
  await page.goto('/muscles')
  expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa']).analyze()).violations).toEqual([])
  await page.goto('/muscles/draft-or-unknown')
  await expect(page.getByRole('heading', { name: 'Muscle not available', exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Browse muscles', exact: true }).click()
  await expect(page).toHaveURL(/\/muscles/)
})
