import { afterEach, describe, expect, it, vi } from "vitest";
import { IDBFactory } from "fake-indexeddb";
import { closeFitnessDatabase, fitnessDatabaseVersion, openFitnessDatabase } from "../src/storage/indexed-db/fitness-database";
import { boundedEditDistance, fuzzyLimit, LocalSearchEngine, searchDocuments, type SearchableDocument } from "../src/features/search/engine";
import type { PublicSearchDocument } from "../src/features/search/domain";
import { canonicalSearchUrl, parseSearchUrl, searchUrlStateSchema } from "../src/features/search/domain";
import { comparisonFamilyFor, validateComparisonEntities } from "../src/features/search/comparison";
import { comparisonFamilies, phase16StoreNames } from "../src/features/saved/schema";
import { addCollectionItem, moveCollectionItem, readSavedStore, readSearchSettings, saveCollection, saveCompareTray, transferCollectionItem, updateCollectionItemNote, writeSearchSetting } from "../src/features/saved/storage";
import vectors from "../DOCS_for_entire_apppliaction/GYM/Phase_16_Search_Favourites_Comparison_Reference_Data.json";

afterEach(() => { closeFitnessDatabase(); vi.unstubAllGlobals(); });
function doc(id: string, title: string, aliases: string[] = [], entityType: SearchableDocument["entityType"] = "route"): SearchableDocument { return { documentId: `${entityType}:${id}`, entityType, entityId: id, entityVersion: null, sourceModule: "phase_01_navigation", route: `/${id}`, title, normalizedTitle: title.toLocaleLowerCase("en-US"), aliases, normalizedAliases: aliases.map((value) => value.toLocaleLowerCase("en-US")), summary: "", keywords: [], headings: [], searchableBody: "", facets: {}, lastReviewedAt: null }; }

describe("Phase 16 search contracts", () => {
  it("checks in all 20 owner reference vectors", () => { expect(vectors.testVectors).toHaveLength(20); });
  it("ranks exact title above aliases and emits match reasons", () => { const results = searchDocuments([doc("alias", "Chest movement", ["bench press"]), doc("title", "Bench press")], { query: "bench press" }).results; expect(results[0]?.document.entityId).toBe("title"); expect(results[1]?.reasons[0]?.field).toBe("aliases"); });
  it("returns one canonical result for an alias and requires every query token", () => { const results = searchDocuments([doc("chickpea", "Chickpea", ["garbanzo bean"]), doc("pea", "Green peas")], { query: "garbanzo" }).results; expect(results.map((result) => result.document.entityId)).toEqual(["chickpea"]); expect(searchDocuments([doc("a", "Bench press")], { query: "bench unknown" }).total).toBe(0); });
  it("does not fuzzy-match short or numeric technical tokens", () => { expect(fuzzyLimit("B12")).toBe(0); expect(fuzzyLimit("leg")).toBe(0); expect(searchDocuments([doc("b1", "B1")], { query: "B12" }).total).toBe(0); });
  it("uses a bounded typo distance for longer tokens", () => { expect(boundedEditDistance("squat", "squatx", 1)).toBe(1); expect(searchDocuments([doc("squat", "Squat")], { query: "squatx" }).total).toBe(1); });
  it("normalizes punctuation and folds accented Latin characters safely", () => { expect(searchDocuments([doc("cafe", "Café")], { query: "cafe" }).total).toBe(1); expect(searchDocuments([doc("push-up", "Push-up")], { query: "push-up" }).total).toBe(1); });
  it("applies entity/module filters, favourites and deterministic sorting", () => { const docs = [doc("z", "Beta", [], "exercise"), { ...doc("a", "Alpha"), sourceModule: "phase_02_anatomy" }]; expect(searchDocuments(docs, { query: "beta", types: ["exercise"] }).results.map((item) => item.document.entityId)).toEqual(["z"]); expect(searchDocuments(docs, { query: "alpha", modules: ["phase_02_anatomy"] }).total).toBe(1); expect(searchDocuments(docs, { query: "alpha", savedOnly: true, favouriteDocumentIds: new Set(["route:a"]) }).total).toBe(1); });
  it("roundtrips validated public URL state and drops invalid state", () => { const state = parseSearchUrl({ q: "squat", type: ["exercise"], sort: "relevance", page: "2" }); expect(searchUrlStateSchema.parse(state)).toMatchObject({ q: "squat", type: ["exercise"], page: 2 }); expect(canonicalSearchUrl(state)).toBe("/search?q=squat&type=exercise&page=2"); expect(parseSearchUrl({ q: "x".repeat(500), invalid: "secret" }).q).toBeUndefined(); });
  it("does not create a public URL for private query state", () => { const url = canonicalSearchUrl(parseSearchUrl({ sort: "relevance", page: 1 })); expect(url).toBe("/search"); expect(url).not.toContain("knee"); });
  it("defines exactly ten comparison families and rejects mixed references", () => { expect(comparisonFamilies).toHaveLength(10); const muscle = { entityType: "muscle" as const, entityId: "m1", sourceModule: "phase_02_anatomy", lastKnownTitle: "Shoulder", lastKnownRoute: "/muscles/shoulder", referenceStatus: "active" as const }; const exercise = { ...muscle, entityType: "exercise" as const, entityId: "e1", sourceModule: "phase_03_exercises" }; expect(comparisonFamilyFor(muscle)).toBe("muscles"); expect(() => validateComparisonEntities("muscles", [muscle, exercise])).toThrow(); });
  it("rejects a fifth comparison item and uncomparable routes", async () => { const factory = new IDBFactory(); vi.stubGlobal("window", { indexedDB: factory }); const route = { entityType: "route" as const, entityId: "/", sourceModule: "phase_01_navigation", lastKnownTitle: "Home", lastKnownRoute: "/", referenceStatus: "active" as const }; await expect(saveCompareTray([route])).rejects.toThrow("cannot be compared"); const exercise = (id: string) => ({ entityType: "exercise" as const, entityId: id, sourceModule: "phase_03_exercises", lastKnownTitle: id, lastKnownRoute: `/exercises/${id}`, referenceStatus: "active" as const }); await expect(saveCompareTray(["1", "2", "3", "4", "5"].map(exercise))).rejects.toThrow("at most four"); });
  it("upgrades the shared IndexedDB schema to v17 while retaining prior stores", async () => { const factory = new IDBFactory(); vi.stubGlobal("window", { indexedDB: factory }); const db = await openFitnessDatabase(); expect(fitnessDatabaseVersion).toBe(17); for (const store of phase16StoreNames) expect(db.objectStoreNames.contains(store)).toBe(true); expect(db.objectStoreNames.contains("bodyWeightLogs")).toBe(true); expect(db.objectStoreNames.contains("workoutSessions")).toBe(true); for (const store of ["phase17Settings", "phase17BackupReceipts", "phase17RestoreJournal", "phase17AuditEvents", "phase17ImportConflicts", "phase17DataHealthCache"]) expect(db.objectStoreNames.contains(store)).toBe(true); });
  it("defaults private search off and clears its cached records when disabled", async () => { const factory = new IDBFactory(); vi.stubGlobal("window", { indexedDB: factory }); expect((await readSearchSettings()).privateSearchEnabled).toBe(false); const db = await openFitnessDatabase(), tx = db.transaction("phase16PrivateSearchCache", "readwrite"); tx.objectStore("phase16PrivateSearchCache").put({ cacheKey: "private:session1" }); await new Promise<void>((resolve) => { tx.oncomplete = () => resolve(); }); await writeSearchSetting("privateSearchEnabled", false); const count = await new Promise<number>((resolve, reject) => { const request = db.transaction("phase16PrivateSearchCache", "readonly").objectStore("phase16PrivateSearchCache").count(); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); expect(count).toBe(0); });
  it("creates, orders, annotates, sorts, moves and copies collection references locally", async () => { const factory = new IDBFactory(); vi.stubGlobal("window", { indexedDB: factory }); const first = await saveCollection({ name: "Learning" }), second = await saveCollection({ name: "Later" }), entity = (id: string) => ({ entityType: "route" as const, entityId: id, sourceModule: "phase_01_navigation", lastKnownTitle: id.toUpperCase(), lastKnownRoute: `/${id}`, referenceStatus: "active" as const }); const one = await addCollectionItem(first.id, entity("alpha")), two = await addCollectionItem(first.id, entity("beta")); await moveCollectionItem(two.id, -1); await updateCollectionItemNote(two.id, "private collection note"); await saveCollection({ id: first.id, name: first.name, sortMode: "title" }); await transferCollectionItem(two.id, second.id, true); expect((await readSavedStore("phase16CollectionItems")).find((row) => row.id === two.id)?.note).toBe("private collection note"); expect((await readSavedStore("phase16CollectionItems")).filter((row) => row.collectionId === first.id).map((row) => Number(row.position)).sort()).toEqual([0, 1]); await transferCollectionItem(one.id, second.id); expect((await readSavedStore("phase16CollectionItems")).filter((row) => row.collectionId === first.id)).toHaveLength(1); expect((await readSavedStore("phase16CollectionItems")).filter((row) => row.collectionId === second.id)).toHaveLength(2); });
  it("benchmarks a 5,000-document indexed local query", async () => { const docs = Array.from({ length: 5000 }, (_, index) => doc(String(index), `Exercise guide ${index} strength movement`)); const engine = new LocalSearchEngine(), start = performance.now(); await engine.build(docs as unknown as PublicSearchDocument[]); const builtAt = performance.now(), response = await engine.search({ query: "strength 4999", pageSize: 20 }); const elapsed = performance.now() - builtAt; console.info(`Phase 16 5k-document local index build: ${(builtAt - start).toFixed(1)}ms; query: ${elapsed.toFixed(1)}ms`); expect(response.total).toBe(1); expect(response.results[0]?.document.entityId).toBe("4999"); expect(elapsed).toBeLessThan(1000); engine.dispose(); });
  it("searches through the serialized inverted postings while preserving ranking", async () => { const engine = new LocalSearchEngine(), docs = [doc("one", "Strength training", ["resistance work"]), doc("two", "Training strength")]; await engine.build(docs as unknown as PublicSearchDocument[], { strength: [0, 1], training: [0, 1], resistance: [0], work: [0] }); const response = await engine.search({ query: "strength" }); expect(response.results.map((item) => item.document.entityId)).toEqual(["one", "two"]); engine.dispose(); });
});
