import type {
  Product,
  Label,
  Intake,
  Trial,
  AdverseEvent,
} from "../src/features/supplements/schema";
export const now = "2026-10-05T10:00:00Z";
export const product: Product = {
  id: "synthetic-product",
  displayName: "Synthetic label fixture",
  brand: null,
  purchaseCountry: null,
  currentLabelVersionId: "synthetic-label",
  createdAt: now,
  updatedAt: now,
  productType: "other",
  notes: "Test data, not supplement evidence",
  archived: false,
  revision: 1,
};
export const label: Label = {
  id: "synthetic-label",
  personalProductId: product.id,
  versionNumber: 1,
  capturedAt: now,
  servingSizeText: "Synthetic one serving",
  servingsPerContainer: null,
  ingredients: [
    {
      ingredientIdentityId: null,
      labelName: "Synthetic amount",
      form: null,
      amount: 0,
      unit: "mg",
      amountDisclosure: "exact",
      sourceText: "Test fixture only",
    },
  ],
  otherIngredientsText: null,
  lotNumber: "LOT-TEST",
  expiryDate: null,
  certifications: [],
  warningsText: null,
  labelImageReferences: [],
  notes: "Not clinical evidence",
  immutable: true,
  allergensText: null,
  manufacturerText: null,
  servingMassGrams: null,
  images: [],
  changeReason: "Test capture",
};
export const trial: Trial = {
  id: "synthetic-trial",
  title: "Synthetic observation",
  labelVersionId: label.id,
  ingredientIdentityIds: [],
  reasonForTrial: "Test",
  primaryOutcomeIds: ["personal-test"],
  baselineStartDate: null,
  trialStartDate: "2026-10-05",
  plannedEndDate: null,
  actualEndDate: null,
  status: "active",
  plannedProtocolText: "No clinical protocol",
  professionalReview: "not_recorded",
  stopRules: [],
  notes: "Test",
  createdAt: now,
  updatedAt: now,
  labelSnapshot: label,
  observations: [],
  contextLinks: [],
  revision: 1,
};
export const intake: Intake = {
  id: "synthetic-intake",
  localDate: "2026-10-05",
  timezone: "UTC",
  takenAt: now,
  trialId: trial.id,
  labelVersionId: label.id,
  servings: 1,
  servingText: label.servingSizeText,
  ingredientSnapshot: label.ingredients,
  contextTags: [],
  notes: "Test",
  createdAt: now,
  updatedAt: now,
  productSnapshot: product,
  labelSnapshot: label,
  revision: 1,
  correctionReason: "",
  history: [],
};
export const event: AdverseEvent = {
  id: "synthetic-event",
  localDate: "2026-10-05",
  timezone: "UTC",
  onsetAt: now,
  severity: "urgent_or_emergency",
  symptoms: ["Synthetic test concern"],
  relatedIntakeLogIds: [intake.id],
  suspectedProductIds: [product.id],
  actionTaken: [],
  resolvedAt: null,
  professionalCare: "unknown",
  reportingJurisdiction: null,
  externalReportReference: null,
  notes: "Synthetic, not clinical observation",
  createdAt: now,
  updatedAt: now,
  stopSignals: ["other_urgent_concern"],
  labelSnapshots: [label],
  revision: 1,
};
