export type MetricDefinition = {
  metricId: string;
  domain: "body" | "nutrition" | "workouts" | "recovery" | "cardio";
  label: string;
  unit: string;
  formula: string;
  methodVersion: string;
  status: "implemented" | "unavailable";
  included: string;
  excluded: string;
  minimumSample: string;
  dateGrouping: string;
  compatibility: string;
  sourceStores: readonly string[];
};
export const phase15Metrics: readonly MetricDefinition[] = [
  { metricId: "body.weight.daily_median", domain: "body", label: "Daily body-weight median", unit: "kg", formula: "Median of all active weight readings on the same recorded local date.", methodVersion: "weight-daily-median-v1", status: "implemented", included: "Active user-entered or imported weight readings.", excluded: "Soft-deleted records.", minimumSample: "One or more readings for a daily median.", dateGrouping: "Recorded local date; timestamp and IANA time zone retained.", compatibility: "Same-day readings grouped; no lowest-value selection.", sourceStores: ["bodyWeightLogs"] },
  { metricId: "weight.moving_average", domain: "body", label: "Weight trend average", unit: "kg", formula: "Arithmetic mean of daily medians within the selected inclusive calendar window.", methodVersion: "weight-trend-7-v1 / weight-trend-28-v1", status: "implemented", included: "Measured dates in the requested local-date window.", excluded: "Missing dates are omitted; no interpolation.", minimumSample: "At least 3 measured days for 7 days; at least 10 for 28 days.", dateGrouping: "Inclusive 7- or 28-calendar-day window.", compatibility: "Canonical kg and local-date medians.", sourceStores: ["bodyWeightLogs"] },
  { metricId: "body.bmi_screening", domain: "body", label: "BMI screening value", unit: "kg/m²", formula: "Weight in kg ÷ (explicit measured height in metres)².", methodVersion: "bmi-screening-v1", status: "implemented", included: "Explicit dated height and a measured weight.", excluded: "No inferred height; not body fat or a diagnosis.", minimumSample: "One height and one weight.", dateGrouping: "Uses most recent explicit local height and weight records.", compatibility: "Canonical kg and cm conversion to metres.", sourceStores: ["bodyWeightLogs", "heightMeasurements"] },
  { metricId: "circumference.replicate_median", domain: "body", label: "Circumference session median", unit: "mm", formula: "Median of 1–5 recorded circumference replicates.", methodVersion: "circumference-replicate-median-v1", status: "implemented", included: "All recorded replicates in one session.", excluded: "No protocol mixing in an individual trend group.", minimumSample: "One replicate per session.", dateGrouping: "Recorded local date.", compatibility: "Same site, protocol/version, side, posture and breathing phase.", sourceStores: ["circumferenceSessions"] },
  { metricId: "nutrition.energy.complete_day_average", domain: "nutrition", label: "Complete-day energy mean", unit: "kcal", formula: "Arithmetic mean of quantified daily totals on dates explicitly reviewed complete.", methodVersion: "complete-nutrition-day-average-v1", status: "implemented", included: "Nutrition records linked to explicitly complete-for-analysis dates.", excluded: "Partial and unknown dates; null nutrient totals.", minimumSample: "At least one quantified complete date.", dateGrouping: "Nutrition module local date and frozen day values.", compatibility: "Recorded source nutrient values; unknown and zero remain distinct.", sourceStores: ["nutritionDays", "foodLogEntries", "nutritionDayReviews"] },
  { metricId: "workouts.completed_sessions", domain: "workouts", label: "Completed workout sessions", unit: "sessions", formula: "Count of sessions with completed status.", methodVersion: "completed-workout-session-count-v1", status: "implemented", included: "Completed source sessions.", excluded: "Abandoned, active, paused, and deleted sessions reported separately or omitted.", minimumSample: "No minimum; zero is valid.", dateGrouping: "Workout session local date.", compatibility: "Source status values are retained.", sourceStores: ["workoutSessions"] },
  { metricId: "recovery.sleep_duration_median", domain: "recovery", label: "Recorded sleep-duration median", unit: "min", formula: "Median of recorded sleep-duration values.", methodVersion: "sleep-duration-median-v1", status: "implemented", included: "Numeric recorded duration values only.", excluded: "Unavailable or null values.", minimumSample: "One numeric value.", dateGrouping: "Recovery module sleep date.", compatibility: "Sleep source and calculation values remain visible.", sourceStores: ["sleepLogs"] },
  { metricId: "cardio.completed_minutes_by_modality", domain: "cardio", label: "Completed cardio duration by modality", unit: "min", formula: "Sum exact completed-session seconds ÷ 60, grouped by recorded modality.", methodVersion: "cardio-modality-duration-v1", status: "implemented", included: "Completed sessions with recorded exact elapsed seconds.", excluded: "Other statuses, null durations, and all calorie/VO₂max estimates.", minimumSample: "No minimum; zero is valid.", dateGrouping: "Session date and modality.", compatibility: "Modality groups remain separate.", sourceStores: ["cardioSessions"] },
  { metricId: "strength.exercise_compatible_pr", domain: "workouts", label: "Exercise-specific loaded set records", unit: "kg / kg·reps", formula: "Heaviest load and highest external load × reps among compatible completed sets.", methodVersion: "phase6-compatible-exercise-pr-v1", status: "implemented", included: "Completed load-reps sets for compatible exercise identities and load scopes.", excluded: "Warm-up, technique, bodyweight, assisted, duration, distance and uncompleted sets.", minimumSample: "One compatible completed set.", dateGrouping: "Source workout local date.", compatibility: "Exercise key, performance mode and load scope remain separate; no 1RM estimate.", sourceStores: ["workoutSessions"] },
];
