import { useEffect, useRef, useState, type FormEvent } from "react";
import { Link } from "@tanstack/react-router";
import { createBackup, clearLocalData, downloadBackup, encodeCsv, inspectLocalData, previewBackup, readDataHistory, recordBackupReceipt, requestPersistentStorage, restoreBackup, resumeRestore, rollbackRestore, type DataInventory } from "./service";
import { openFitnessDatabase } from "../../storage/indexed-db/fitness-database";

export type DataSection = "home" | "backup" | "restore" | "export" | "storage" | "health" | "reset" | "history";
const headings: Record<DataSection, [string, string]> = {
  home: ["Your local data", "Back up, restore, export and inspect records saved in this browser."],
  backup: ["Create a backup", "Create a portable copy of supported Fitness OS records on this device."],
  restore: ["Restore a backup", "Validate an archive before choosing any local changes."],
  export: ["Export CSV", "Export table rows for spreadsheets. Spreadsheet-safe mode is on by default."],
  storage: ["Storage inventory", "Inspect local databases and browser-reported storage estimates."],
  health: ["Data health", "Check local database availability and recoverable operations."],
  reset: ["Clear local data", "Remove Fitness OS records stored in this browser profile."],
  history: ["Data history", "Review successful backup receipts and data-management events."],
};
function formatBytes(value?: number) { if (value === undefined) return "Not available"; const units = ["bytes", "KB", "MB", "GB"]; let size = value, index = 0; while (size >= 1024 && index < units.length - 1) { size /= 1024; index++; } return `${size.toFixed(index ? 1 : 0)} ${units[index]}`; }
function downloadText(filename: string, content: string, type: string) { const url = URL.createObjectURL(new Blob([content], { type })), link = document.createElement("a"); link.href = url; link.download = filename; document.body.append(link); link.click(); link.remove(); setTimeout(() => URL.revokeObjectURL(url), 1000); }

export function DataManagementPage({ section }: { section: DataSection }) {
  const [inventory, setInventory] = useState<DataInventory | null>(null), [busy, setBusy] = useState(false), [clearing, setClearing] = useState(false), [message, setMessage] = useState(""), [error, setError] = useState(""), [selected, setSelected] = useState<string[] | null>(null), [media, setMedia] = useState(false), [gzip, setGzip] = useState(false), [parsed, setParsed] = useState<unknown>(), [preview, setPreview] = useState<Awaited<ReturnType<typeof previewBackup>> | null>(null), [history, setHistory] = useState<Record<string, Record<string, unknown>[]>>({});
  async function refresh() { setError(""); try { await openFitnessDatabase(); setInventory(await inspectLocalData()); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not inspect local storage."); } }
  useEffect(() => { if (["home", "backup", "storage", "health"].includes(section)) void Promise.resolve().then(refresh); if (section === "home" || section === "history" || section === "health") void readDataHistory().then(setHistory).catch((cause: unknown) => setError(cause instanceof Error ? cause.message : "Could not read data history.")); }, [section]);
  async function backup() {
    setBusy(true); setError(""); setMessage("");
    try { const result = await createBackup({ ...(selected ? { selectedDatabases: selected } : {}), fullMedia: media, gzip }); const delivery = await downloadBackup(result); if (delivery === "saved") { await recordBackupReceipt(result, "file-picker"); setMessage(`Backup saved successfully. ${result.manifest.humanSummary}`); } else setMessage(`Backup download was started. The browser cannot confirm that it reached a file, so no success receipt was recorded. ${result.manifest.humanSummary}`); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Backup could not be created."); } finally { setBusy(false); }
  }
  const fileGeneration = useRef(0);
  useEffect(() => () => { fileGeneration.current++; }, [section]);
  async function loadFile(file?: File) {
    const generation = ++fileGeneration.current;
    setError(""); setMessage(""); setPreview(null); setParsed(undefined); if (!file) return;
    try { let text: string; if (file.name.endsWith(".gz")) { const stream = new Blob([await file.arrayBuffer()]).stream().pipeThrough(new DecompressionStream("gzip")); text = await new Response(stream).text(); } else text = await file.text(); if (generation !== fileGeneration.current) return; const input: unknown = JSON.parse(text); const result = await previewBackup(input); if (generation !== fileGeneration.current) return; setParsed(input); setPreview(result); setMessage(result.errors.length ? "Preview found issues. No local data was changed." : "Preview passed. No local data was changed."); }
    catch (cause) { if (generation === fileGeneration.current) setError(cause instanceof Error ? cause.message : "The selected file is invalid or cannot be read."); }
  }
  async function restore(mode: "keep-existing" | "replace") { if (!parsed) return; if (mode === "replace" && !window.confirm("Replace records in every selected store with the backup contents? This cannot be undone.")) return; setBusy(true); setError(""); try { const result = await restoreBackup(parsed, mode); setMessage(`Restore completed in ${result.databases} database(s), covering ${result.records} incoming records.`); setParsed(undefined); setPreview(null); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Restore failed."); } finally { setBusy(false); } }
  async function makeCsv(mode: "safe" | "raw") { setBusy(true); setError(""); try { const backup = await createBackup(), rows = backup.payload.modules.flatMap((module) => module.stores.flatMap((store) => store.records.map((record) => ({ database: store.databaseName, store: store.storeId, recordId: record.recordId, value: JSON.stringify(record.value) })))); downloadText(`fitness-os-data-${new Date().toISOString().slice(0, 10)}-${mode}.csv`, encodeCsv(rows, mode), "text/csv;charset=utf-8"); setMessage(`${rows.length} rows exported. The browser download has started.`); } catch (cause) { setError(cause instanceof Error ? cause.message : "CSV export failed."); } finally { setBusy(false); } }
  async function persist() { setError(""); try { const granted = await requestPersistentStorage(); setMessage(granted === null ? "This browser does not support a persistent-storage request." : granted ? "The browser granted persistent storage for this origin." : "The browser denied persistent storage. The app remains available; keep a backup outside this browser."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Persistent storage request failed."); } }
  async function recoverRestore(action: "resume" | "rollback", id: string) { setBusy(true); setError(""); try { const result = action === "resume" ? await resumeRestore(id) : await rollbackRestore(id); setMessage(action === "resume" ? `Restore resumed and completed in ${result.databases} database(s).` : `Restore rolled back across ${result.databases} database(s).`); setHistory(await readDataHistory()); } catch (cause) { setError(cause instanceof Error ? cause.message : "Restore recovery failed and remains journaled."); } finally { setBusy(false); } }
  async function clear(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = new FormData(event.currentTarget), backupChoice = values.get("backupChoice"), confirmation = String(values.get("confirmation") ?? ""); if (!backupChoice) { setError("Choose whether you have an external backup before clearing data."); return; } if (confirmation !== "CLEAR LOCAL DATA") { setError("Type CLEAR LOCAL DATA exactly to continue."); return; } setClearing(true); setError(""); try { const removed = await clearLocalData(confirmation); setMessage(`Cleared ${removed.length} Fitness OS database(s) and known local preferences.`); setInventory({ supported: true, databases: [], unknownDatabaseNames: [], warnings: [] }); } catch (cause) { setError(cause instanceof Error ? cause.message : "Local data could not be cleared."); } finally { setClearing(false); } }
  const [title, description] = headings[section];
  return <div className="page data-management-page"><header className="page-heading"><div><span className="eyebrow">DEVICE LOCAL · BACKUP & EXPORT</span><h1>{title}</h1><p>{description}</p></div><Link to="/settings" className="button secondary">Settings</Link></header>
    <nav className="data-tabs" aria-label="Data management">{([["/settings/data", "Overview"], ["/settings/data/backup", "Backup"], ["/settings/data/restore", "Restore"], ["/settings/data/export", "CSV export"], ["/settings/data/storage", "Storage"], ["/settings/data/health", "Health"], ["/settings/data/history", "History"], ["/settings/data/reset", "Clear data"]] as const).map(([to, label]) => <Link to={to} key={to} className={to.endsWith(section) || (section === "home" && to === "/settings/data") ? "active" : ""}>{label}</Link>)}</nav>
    {error && <div className="data-alert error" role="alert">{error}</div>}{message && <div className="data-alert" role="status" aria-live="polite">{message}</div>}
    {section === "home" && <><section className="data-panel backup-reminder"><h2>{(history.phase17BackupReceipts ?? []).length ? "Your last confirmed backup" : "Create your first backup"}</h2><p>{(history.phase17BackupReceipts ?? []).length ? `Last saved ${(history.phase17BackupReceipts ?? []).map((row) => String(row.createdAt)).sort().at(-1)}. Keep an up-to-date copy outside this browser.` : "No successful file-save receipt is recorded yet. Browser storage can be cleared or evicted."}</p><Link className="button primary" to="/settings/data/backup">Create a backup</Link></section><section className="data-card-grid">{([["/settings/data/backup", "Create a backup", "Save your local records to a file."], ["/settings/data/restore", "Restore records", "Review an archive before writing."], ["/settings/data/export", "Export CSV", "Create spreadsheet-ready table exports."], ["/settings/data/storage", "Storage inventory", "Inspect local stores and approximate usage."], ["/settings/data/health", "Data health", "Check availability and recovery state."], ["/settings/data/history", "Backup history", "Review saved backup receipts."], ["/settings/data/reset", "Clear local data", "Remove this app’s browser data."], ["/settings/data/storage", "Keep data on this device", "Ask the browser for persistent storage."]] as const).map(([to, label, text]) => <Link className="data-action-card" to={to} key={label}><strong>{label}</strong><span>{text}</span></Link>)}</section></>}
    {section === "backup" && <section className="data-panel"><h2>Portable backup</h2><p>Personal records stay on this device until you choose a local file destination. Backups are not encrypted; keep downloaded copies private.</p><div className="data-estimate"><strong>{inventory?.databases.reduce((sum, db) => sum + db.stores.filter((store) => store.includedByDefault).reduce((n, store) => n + store.count, 0), 0) ?? "…"}</strong><span>records currently eligible for backup</span></div><fieldset className="data-options"><legend>Backup options</legend>{inventory?.databases.filter((db) => db.stores.some((store) => store.includedByDefault)).map((db) => { const allNames = inventory.databases.filter((item) => item.stores.some((store) => store.includedByDefault)).map((item) => item.name), checked = selected === null || selected.includes(db.name); return <label key={db.name}><input type="checkbox" checked={checked} onChange={(event) => { const active = selected ?? allNames; setSelected(event.target.checked ? [...new Set([...active, db.name])] : active.filter((name) => name !== db.name)); }} /><span>{db.name} <small>{db.stores.filter((store) => store.includedByDefault).reduce((sum, store) => sum + store.count, 0)} records</small></span></label>; })}<label><input type="checkbox" checked={media} onChange={(event) => setMedia(event.target.checked)} /><span>Include progress-photo binary media<small>Can make the backup much larger</small></span></label><label><input type="checkbox" checked={gzip} disabled={typeof CompressionStream === "undefined"} onChange={(event) => setGzip(event.target.checked)} /><span>Compress with gzip<small>{typeof CompressionStream === "undefined" ? "Not supported in this browser" : "Requires browser compression support"}</small></span></label></fieldset><button className="button primary" disabled={busy} onClick={() => void backup()}>{busy ? "Creating backup…" : "Create backup file"}</button><p className="data-footnote">SHA-256 detects accidental corruption. It does not prove who made a file or conceal its contents. Rebuildable caches, active timers, private search cache and tab-only keys are excluded.</p></section>}
    {section === "restore" && <section className="data-panel"><label className="file-picker">Backup file<input type="file" disabled={busy} accept=".json,.gz,application/json,application/gzip" onChange={(event) => void loadFile(event.currentTarget.files?.[0])} /></label>{preview && <div className="restore-preview"><h2>{preview.errors.length ? "Review required" : "Preview passed"}</h2><p>{preview.backup.manifest.humanSummary ?? "Backup archive"} · SHA-256 and schema checked · 0 writes during preview</p>{preview.errors.length > 0 && <ul>{preview.errors.map((item) => <li key={item}>{item}</li>)}</ul>}{preview.warnings.map((item) => <p key={item} className="data-footnote">{item}</p>)}{preview.conflicts.length > 0 && <div className="inventory-table" tabIndex={0} role="region" aria-label="Scrollable record table"><table><thead><tr><th>Database / store</th><th>Incoming</th><th>Existing</th></tr></thead><tbody>{preview.conflicts.map((item) => <tr key={`${item.databaseName}/${item.storeId}`}><td>{item.databaseName} / {item.storeId}</td><td>{item.incoming}</td><td>{item.existing}</td></tr>)}</tbody></table></div>}{preview.errors.length === 0 && <div className="data-actions"><button className="button primary" disabled={busy} onClick={() => void restore("keep-existing")}>Keep existing records</button><button className="button danger" disabled={busy} onClick={() => void restore("replace")}>Replace matching stores</button></div>}</div>}<p className="data-footnote">This restore does not support import-as-copy because the app has no verified ID remapper for every record relationship. A multi-database restore is journaled; browser storage cannot make independent databases globally atomic.</p></section>}
    {section === "export" && <section className="data-panel"><h2>CSV profile</h2><p>Exports one row per local record with database and store columns. CSV is a table-oriented view; use JSON backup for a restorable archive.</p><div className="data-actions"><button className="button primary" disabled={busy} onClick={() => void makeCsv("safe")}>Export spreadsheet-safe CSV</button><button className="button secondary" disabled={busy} onClick={() => { if (window.confirm("Raw CSV may be interpreted as a spreadsheet formula. Continue?")) void makeCsv("raw"); }}>Export raw machine CSV</button></div><p className="data-footnote">Safe mode prefixes formula-like user text. Raw mode preserves original cell content and requires the warning confirmation.</p></section>}
    {section === "storage" && <section className="data-panel"><h2>Browser storage estimate</h2><p>Usage and quota are approximate browser-reported values and may change with the browser, device, private mode or other tabs.</p><dl className="storage-metrics"><div><dt>Approximate use</dt><dd>{formatBytes(inventory?.storageEstimate?.usage)}</dd></div><div><dt>Approximate quota</dt><dd>{formatBytes(inventory?.storageEstimate?.quota)}</dd></div><div><dt>Persistent storage</dt><dd>{inventory?.storageEstimate?.persisted === null || !inventory?.storageEstimate ? "Not available" : inventory.storageEstimate.persisted ? "Granted" : "Not granted"}</dd></div></dl><button className="button secondary" onClick={() => void persist()}>Request persistent storage</button><InventoryTable inventory={inventory} /></section>}
    {section === "health" && <section className="data-panel"><h2>Local data health</h2><p>{inventory?.supported ? "IndexedDB is available." : "IndexedDB is unavailable."} Inventory errors and unknown databases are surfaced below. Unknown data is never automatically removed.</p><InventoryTable inventory={inventory} /><button className="button secondary" onClick={() => void refresh()}>Refresh health check</button>{(history.phase17RestoreJournal ?? []).map((row) => <article className="restore-journal" key={String(row.id)}><h3>Restore needs attention</h3><p>Status: {String(row.status)} · completed databases: {Array.isArray(row.completedDatabases) ? row.completedDatabases.length : 0}</p><div className="data-actions"><button className="button primary" disabled={busy} onClick={() => void recoverRestore("resume", String(row.id))}>Resume restore</button><button className="button danger" disabled={busy} onClick={() => { if (window.confirm("Restore the pre-import snapshot for all journaled stores?")) void recoverRestore("rollback", String(row.id)); }}>Roll back restore</button></div></article>)}<details><summary>Repair guidance</summary><p>Database schema upgrades are performed by each module’s versioned migration. If an operation is blocked, close other app tabs and retry. The app does not delete unrecognized stores or invent repairs for unknown records.</p></details></section>}
    {section === "reset" && <section className="data-panel danger-panel"><h2>Clear this browser profile</h2><p>This permanently deletes the app’s known Fitness OS databases and selected small preferences for this origin. It cannot clear unrelated browser data. Export a backup to a location outside this browser first if you may need these records later.</p><Link className="button secondary" to="/settings/data/backup">Create a backup first</Link><form onSubmit={(event) => void clear(event)}><fieldset className="data-options"><legend>Backup choice (required)</legend><label><input type="radio" name="backupChoice" value="saved" required /><span>I saved a backup outside this browser</span></label><label><input type="radio" name="backupChoice" value="none" /><span>I understand and want to clear without a backup</span></label></fieldset><label className="typed-confirm">Type <code>CLEAR LOCAL DATA</code> to confirm<input name="confirmation" autoComplete="off" required pattern="CLEAR LOCAL DATA" /></label><button className="button danger" type="submit" disabled={clearing}>Clear Fitness OS data</button></form></section>}
    {section === "history" && <section className="data-panel"><h2>Successful backup receipts</h2>{(history.phase17BackupReceipts ?? []).length ? <div className="inventory-table" tabIndex={0} role="region" aria-label="Scrollable record table"><table><thead><tr><th>Created</th><th>Profile</th><th>Records</th><th>Delivery</th></tr></thead><tbody>{(history.phase17BackupReceipts ?? []).map((row) => <tr key={String(row.id)}><td>{String(row.createdAt)}</td><td>{String(row.profile)}</td><td>{String(row.recordCount)}</td><td>{String(row.delivery)}</td></tr>)}</tbody></table></div> : <p>No confirmed file-save receipts are available yet. Browser downloads that cannot report completion are not recorded as successful.</p>}<h2>Data-management events</h2><ul className="data-history">{(history.phase17AuditEvents ?? []).map((row) => <li key={String(row.id)}><strong>{String(row.eventType)}</strong><span>{String(row.occurredAt)}</span></li>)}</ul></section>}
  </div>;
}
function InventoryTable({ inventory }: { inventory: DataInventory | null }) { return <div className="inventory-table" tabIndex={0} role="region" aria-label="Scrollable record table"><table><thead><tr><th>Database</th><th>Version</th><th>Store</th><th>Records</th><th>Backup</th></tr></thead><tbody>{inventory?.databases.flatMap((db) => db.warning ? [<tr key={db.name}><td>{db.name}</td><td>{db.version}</td><td colSpan={3}>{db.warning}</td></tr>] : db.stores.map((store) => <tr key={`${db.name}/${store.name}`}><td>{db.name}</td><td>{db.version}</td><td>{store.name}{store.media && " (binary media)"}</td><td>{store.count}</td><td>{store.includedByDefault ? "Portable" : "Excluded"}</td></tr>))}</tbody></table>{inventory?.unknownDatabaseNames.length ? <p>Unrecognized databases detected and left untouched: {inventory.unknownDatabaseNames.join(", ")}</p> : null}{inventory?.warnings.map((warning) => <p key={warning} role="status">{warning}</p>)}</div>; }
