import { useState } from 'react'
import { anatomyTaxonomy } from './repository'
import { usePreferences } from '../../components/app-shell/preferences'
const spots: Record<string, { top: number; left: number }> = {
  region_neck: { top: 12, left: 3 }, region_shoulder: { top: 22, left: 52 }, region_chest: { top: 31, left: 3 },
  region_upper_back: { top: 31, left: 3 }, region_lower_back: { top: 49, left: 52 }, region_upper_arm: { top: 40, left: 52 },
  region_forearm_grip: { top: 50, left: 3 }, region_core_trunk: { top: 41, left: 3 }, region_hip_gluteal: { top: 57, left: 52 },
  region_front_thigh: { top: 68, left: 3 }, region_back_thigh: { top: 68, left: 3 }, region_inner_outer_thigh: { top: 76, left: 52 }, region_lower_leg: { top: 86, left: 3 },
}
export function BodyRegionSelector({ selected, onSelect }: { selected: string; onSelect: (id: string) => void }) {
  const { hydrated } = usePreferences()
  const [side, setSide] = useState<'anterior' | 'posterior'>('anterior')
  const visible = anatomyTaxonomy.regions.filter((region) => region.defaultVisibility === 'multiple' || region.defaultVisibility === side)
  return <section className="body-browser" aria-labelledby="body-browser-title"><div className="body-browser-header"><div><span className="eyebrow">START WITH A REGION</span><h2 id="body-browser-title">Explore the body</h2></div><div className="segmented" aria-label="Body orientation">{(['anterior', 'posterior'] as const).map((orientation) => <button key={orientation} disabled={!hydrated} aria-pressed={side === orientation} onClick={() => setSide(orientation)}>{orientation === 'anterior' ? 'Front' : 'Back'}</button>)}</div></div><div className="body-browser-grid"><figure className="body-figure"><div className="body-map"><svg viewBox="0 0 300 520" role="img" aria-labelledby="body-title body-desc"><title id="body-title">{`${side === 'anterior' ? 'Front' : 'Back'} body-region navigation silhouette`}</title><desc id="body-desc">An original abstract silhouette to navigate body regions. Use the labelled region buttons or the equivalent text list. This is not a precise anatomy diagram.</desc><circle cx="150" cy="47" r="26" /><path d="M136 77h28l4 22 40 17 26 72 12 90-17 9-23-94-17-36-8 82 13 36-15 123-10 83 10 22-31 1-4-130-5-69-5 69-4 130-31-1 10-22-10-83-15-123 13-36-8-82-17 36-23 94-17-9 12-90 26-72 40-17z" /></svg>{visible.map((region) => { const spot = spots[region.id]; return spot && <button className={`map-region ${region.id === selected ? 'selected' : ''}`} key={region.id} disabled={!hydrated} aria-pressed={selected === region.id} aria-label={`Select ${region.displayName} on body map`} style={{ top: `${spot.top}%`, left: `${spot.left}%` }} onClick={() => onSelect(region.id)}>{region.displayName}{selected === region.id && <span aria-hidden="true">✓</span>}</button> })}</div><figcaption>Original abstract navigation aid · project-owned vector. Region locations are approximate.</figcaption></figure><div className="region-text-list"><h3>Browse by region</h3><p>The text list and body selector use the same filters.</p><div className="region-grid">{anatomyTaxonomy.regions.map((region) => <button key={region.id} disabled={!hydrated} aria-pressed={selected === region.id} onClick={() => onSelect(region.id)}>{region.displayName}{selected === region.id && <span aria-hidden="true">✓</span>}</button>)}</div>{selected && <button className="button secondary" onClick={() => onSelect('')}>Show all regions</button>}</div></div></section>
}
