import { appConfig } from '../config/app'
import { LinkCard } from './common/primitives'
import { modules, navigationItems } from '../data/navigation'
import { Icon, type IconName } from './common/icon'

const pillars: { title: string; subtitle: string; description: string; href: string; icon: IconName; items: string[]; tone: string }[] = [
  { title: 'Learn', subtitle: 'UNDERSTAND THE WHY', description: 'Make sense of movement, muscles and the science behind training.', href: '/learn', icon: 'book', items: ['Muscles & anatomy', 'Exercise library', 'Training science'], tone: 'sage' },
  { title: 'Train', subtitle: 'PUT KNOWLEDGE TO WORK', description: 'Turn a plan into practice, with training that fits your life.', href: '/programs', icon: 'dumbbell', items: ['Workout programs', 'Session workspace', 'Cardio & conditioning'], tone: 'sand' },
  { title: 'Eat', subtitle: 'MAKE INFORMED CHOICES', description: 'Connect foods, nutrients and practical meal planning in one place.', href: '/foods', icon: 'leaf', items: ['Food encyclopedia', 'Nutrient library', 'Meals & recipes'], tone: 'lavender' },
]

export function HomePage() {
  return <div className="page home-page">
    <div className="page-heading"><div><div className="eyebrow">{appConfig.name.toUpperCase()} / YOUR KNOWLEDGE & WORKSPACE</div><h1>Your fitness, connected.</h1><p>Knowledge, planning and progress. One space, built around you.</p></div><span className="phase-chip"><span className="status-dot" />Saved on your device</span></div>
    <div className="home-grid"><div className="home-primary">
      <section className="hero" aria-labelledby="hero-title"><div className="hero-content"><span className="hero-eyebrow"><span />THE START OF SOMETHING STRONG</span><h2 id="hero-title">Build knowledge.<br /><em>Make progress.</em></h2><p>A thoughtful home for learning, training and living well. No account needed. Your personal space stays yours.</p><a href="/learn" className="button hero-button">Explore the libraries<Icon name="arrow" size={17} /></a><div className="hero-footnote"><Icon name="sprout" size={15} />Sources and review levels accompany published content.</div></div><div className="hero-art" aria-hidden="true"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="orbit orbit-three" /><div className="art-axis horizontal" /><div className="art-axis vertical" /><div className="art-center"><svg viewBox="0 0 100 100"><path d="M25 69V31h51v10H37v9h32v10H37v9z" fill="currentColor" /></svg></div><span className="orbit-point point-one" /><span className="orbit-point point-two" /></div></section>
      <section className="pillars-section" aria-labelledby="pillars-title"><div className="section-heading"><div><h2 id="pillars-title">A connected approach</h2><p>Start with understanding. Build from there.</p></div><span className="section-count">01 — 03</span></div><div className="pillar-grid">{pillars.map((pillar, index) => <a className="pillar-card" href={pillar.href} key={pillar.title}><div className="pillar-top"><span className={`pillar-icon ${pillar.tone}`}><Icon name={pillar.icon} size={23} /></span><span className="pillar-number">0{index + 1}</span></div><span className="pillar-subtitle">{pillar.subtitle}</span><h3>{pillar.title}<Icon name="external" size={21} /></h3><p>{pillar.description}</p><ul>{pillar.items.map((item) => <li key={item}>{item}</li>)}</ul><span className="planned-label">Explore<Icon name="arrow" size={14} /></span></a>)}</div></section>
      <div className="supporting-links"><a href="/recovery"><span className="support-icon"><Icon name="moon" /></span><span><strong>Room to recover</strong><small>Sleep, mobility & rest</small></span><Icon name="arrow" size={18} /></a><a href="/progress"><span className="support-icon"><Icon name="chart" /></span><span><strong>Progress on your terms</strong><small>Optional, device-local tracking</small></span><Icon name="arrow" size={18} /></a></div>
    </div><aside className="home-rail" aria-label="Getting started and privacy">
      <section className="privacy-card"><span className="privacy-icon"><Icon name="shield" size={26} /></span><span className="eyebrow">BUILT WITH INTENTION</span><h2>Your data.<br />Your ownership.</h2><p>Personal records stay in your browser. No accounts. No automatic cloud sync.</p><ul><li><Icon name="check" size={15} />Explore without signing up</li><li><Icon name="check" size={15} />Choose what you track</li><li><Icon name="check" size={15} />Keep personal data local</li></ul><a href="/settings/data">Manage backups and storage<Icon name="arrow" size={16} /></a></section>
      <section className="roadmap-card"><div className="rail-title"><h2>Start here</h2></div><p>Explore first. Tracking is optional.</p><ol className="roadmap"><li className="current"><span className="roadmap-node"><span /></span><div><small>FIND AN ANSWER</small><strong><a href="/search">Search the libraries</a></strong><p>Browse published foods, nutrients, movement and training topics.</p></div></li><li><span className="roadmap-node" /><div><small>YOUR WORKSPACE</small><strong><a href="/workout">Record a session</a></strong><p>Choose what to track and save it on this device.</p></div></li><li><span className="roadmap-node" /><div><small>KEEP A COPY</small><strong><a href="/settings/data/backup">Create a backup</a></strong><p>Browser storage can be cleared. Keep an exported copy somewhere safe.</p></div></li></ol><a href="/about/sources" className="roadmap-link">Sources and review levels<Icon name="arrow" size={15} /></a></section>
      <div className="foundation-note"><Icon name="help" size={17} /><p>Content is published with sources and a visible review level. Some subjects remain unavailable while source verification is unfinished.</p></div>
    </aside></div>
    <section className="explore-section"><div className="section-heading"><div><h2>Explore by module</h2><p>Training, nutrition, recovery and optional tracking, connected in one place.</p></div></div><div className="module-directory">{["/muscles", "/exercises", "/programs", "/foods", "/nutrients", "/recovery", "/tools"].map((href) => { const entry = navigationItems.find((item) => item.href === href); return entry && <LinkCard key={href} title={modules.find((module) => module.path === href)?.title ?? entry.label} href={href} icon={entry.icon} /> })}</div></section>
  </div>
}
