import { Icon, type IconName } from './common/icon'

const pillars: { title: string; subtitle: string; description: string; href: string; icon: IconName; items: string[]; tone: string }[] = [
  { title: 'Learn', subtitle: 'UNDERSTAND THE WHY', description: 'Make sense of movement, muscles and the science behind training.', href: '/learn', icon: 'book', items: ['Muscles & anatomy', 'Exercise library', 'Training science'], tone: 'sage' },
  { title: 'Train', subtitle: 'PUT KNOWLEDGE TO WORK', description: 'Turn a plan into practice, with training that fits your life.', href: '/train', icon: 'dumbbell', items: ['Workout programs', 'Session workspace', 'Cardio & conditioning'], tone: 'sand' },
  { title: 'Eat', subtitle: 'MAKE INFORMED CHOICES', description: 'Connect foods, nutrients and practical meal planning in one place.', href: '/eat', icon: 'leaf', items: ['Food encyclopedia', 'Nutrient library', 'Meals & recipes'], tone: 'lavender' },
]

export function HomePage() {
  return <div className="page home-page">
    <div className="page-heading"><div><div className="eyebrow">A STRONGER FOUNDATION</div><h1>Your fitness, connected.</h1><p>Knowledge, planning and progress. One space, built around you.</p></div><span className="phase-chip"><span className="status-dot" />Phase 00 · Foundation</span></div>
    <div className="home-grid"><div className="home-primary">
      <section className="hero" aria-labelledby="hero-title"><div className="hero-content"><span className="hero-eyebrow"><span />THE START OF SOMETHING STRONG</span><h2 id="hero-title">Build knowledge.<br /><em>Make progress.</em></h2><p>A thoughtful home for learning, training and living well. No account needed. Your personal space stays yours.</p><a href="/learn" className="button hero-button">Explore the foundation<Icon name="arrow" size={17} /></a><div className="hero-footnote"><Icon name="sprout" size={15} />Growing one thoughtful phase at a time.</div></div><div className="hero-art" aria-hidden="true"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="orbit orbit-three" /><div className="art-axis horizontal" /><div className="art-axis vertical" /><div className="art-center"><svg viewBox="0 0 100 100"><path d="M25 69V31h51v10H37v9h32v10H37v9z" fill="currentColor" /></svg></div><span className="orbit-point point-one" /><span className="orbit-point point-two" /></div></section>
      <section className="pillars-section" aria-labelledby="pillars-title"><div className="section-heading"><div><h2 id="pillars-title">A connected approach</h2><p>Start with understanding. Build from there.</p></div><span className="section-count">01 — 03</span></div><div className="pillar-grid">{pillars.map((pillar, index) => <a className="pillar-card" href={pillar.href} key={pillar.title}><div className="pillar-top"><span className={`pillar-icon ${pillar.tone}`}><Icon name={pillar.icon} size={23} /></span><span className="pillar-number">0{index + 1}</span></div><span className="pillar-subtitle">{pillar.subtitle}</span><h3>{pillar.title}<Icon name="external" size={21} /></h3><p>{pillar.description}</p><ul>{pillar.items.map((item) => <li key={item}>{item}</li>)}</ul><span className="planned-label">Planned module<Icon name="arrow" size={14} /></span></a>)}</div></section>
      <div className="supporting-links"><a href="/recovery"><span className="support-icon"><Icon name="moon" /></span><span><strong>Room to recover</strong><small>Sleep, mobility & rest</small></span><Icon name="arrow" size={18} /></a><a href="/track"><span className="support-icon"><Icon name="chart" /></span><span><strong>Progress on your terms</strong><small>Optional, device-local tracking</small></span><Icon name="arrow" size={18} /></a></div>
    </div><aside className="home-rail" aria-label="Foundation information">
      <section className="privacy-card"><span className="privacy-icon"><Icon name="shield" size={26} /></span><span className="eyebrow">BUILT WITH INTENTION</span><h2>Your data.<br />Your ownership.</h2><p>Personal records will live in your browser. No accounts. No automatic cloud sync.</p><ul><li><Icon name="check" size={15} />Explore without signing up</li><li><Icon name="check" size={15} />Choose what you track</li><li><Icon name="check" size={15} />Keep personal data local</li></ul><a href="/settings">Understand local storage<Icon name="arrow" size={16} /></a></section>
      <section className="roadmap-card"><div className="rail-title"><h2>The build roadmap</h2><span>IN PROGRESS</span></div><p>A considered foundation first.<br />Features follow, phase by phase.</p><ol className="roadmap"><li className="current"><span className="roadmap-node"><span /></span><div><small>PHASE 00 · CURRENT</small><strong>Master foundation</strong><p>Architecture, routes & data rules</p></div></li><li><span className="roadmap-node" /><div><small>PHASE 01 · NEXT</small><strong>Shell & design system</strong><p>Navigation & shared components</p></div></li><li><span className="roadmap-node" /><div><small>PHASE 02 ONWARD</small><strong>Knowledge into action</strong><p>Libraries, plans & optional logs</p></div></li></ol><a href="/learn" className="roadmap-link">Browse planned modules<Icon name="arrow" size={15} /></a></section>
      <div className="foundation-note"><Icon name="help" size={17} /><p>This is the Phase 00 foundation. Feature pages are intentional placeholders while the application takes shape.</p></div>
    </aside></div>
  </div>
}
