import { z } from "zod";
import { searchEntityTypes } from "../search/domain";

const id = z.string().min(1).max(180), timestamp = z.iso.datetime({ offset: true }), text = (limit: number) => z.string().trim().min(1).max(limit);
export const comparisonFamilies = ["muscles", "exercises", "workout_programs", "foods", "nutrients", "recipes", "recovery_methods", "cardio_modalities", "cardio_plans", "supplements"] as const;
export type ComparisonFamily = (typeof comparisonFamilies)[number];
export const entityRefSchema = z.strictObject({ entityType: z.enum(searchEntityTypes), entityId: id, entityVersion: z.string().nullable().optional(), sourceModule: text(80), lastKnownTitle: text(300), lastKnownRoute: z.string().max(500).nullable(), referenceStatus: z.enum(["active", "orphaned", "migrated", "unavailable", "private"]), migrationFromId: z.string().nullable().optional() });
export const favouriteSchema = z.strictObject({ id, entity: entityRefSchema, savedAt: timestamp, updatedAt: timestamp });
export const collectionSchema = z.strictObject({ id, name: text(120), description: z.string().max(1000).nullable().optional(), createdAt: timestamp, updatedAt: timestamp, sortMode: z.enum(["manual", "title", "saved_newest", "saved_oldest"]) });
export const collectionItemSchema = z.strictObject({ id, collectionId: id, entity: entityRefSchema, position: z.number().int().min(0), note: z.string().max(3000).nullable().optional(), addedAt: timestamp, updatedAt: timestamp.nullable().optional() });
export const recentQuerySchema = z.strictObject({ id, normalizedQuery: text(120), displayQuery: text(120), scope: z.enum(["public", "public_and_private"]), publicFilters: z.record(z.string(), z.union([z.string(), z.number(), z.boolean(), z.array(z.unknown()), z.null()])).optional(), resultCount: z.number().int().nonnegative().nullable().optional(), searchedAt: timestamp });
export const recentViewSchema = z.strictObject({ id, entity: entityRefSchema, viewedAt: timestamp });
export const comparisonEntitySchema = z.strictObject({ entity: entityRefSchema, position: z.number().int().min(0).max(3) });
export const savedComparisonSchema = z.strictObject({ id, name: text(160), family: z.enum(comparisonFamilies), entities: z.array(comparisonEntitySchema).min(2).max(4), basis: z.record(z.string(), z.unknown()), selectedMetricIds: z.array(z.string()).optional(), createdAt: timestamp, updatedAt: timestamp, lastOpenedAt: timestamp.nullable().optional(), status: z.enum(["active", "contains_orphan", "incompatible_after_update"]).default("active") });
export const settingSchema = z.strictObject({ key: text(120), value: z.unknown(), updatedAt: timestamp });
export const auditEventSchema = z.strictObject({ id, eventType: z.enum(["favourite_added", "favourite_removed", "collection_created", "collection_updated", "collection_deleted", "collection_item_added", "collection_item_removed", "recent_history_cleared", "comparison_saved", "comparison_updated", "comparison_deleted", "entity_reference_migrated", "imported", "restored", "deleted"]), occurredAt: timestamp, entityType: z.string().max(80), entityId: z.string().max(180), details: z.record(z.string(), z.unknown()).optional() });
export const deletedRecordSchema = z.strictObject({ entityType: z.string().max(80), entityId: id, deletedAt: timestamp, reason: z.string().max(500).nullable().optional() });
export const importConflictSchema = z.strictObject({ id, collection: text(100), entityId: id, resolution: z.literal("kept_existing"), occurredAt: timestamp });
export const phase16BackupSchema = z.strictObject({ schemaVersion: z.literal("1.0.0"), exportedAt: timestamp, moduleId: z.literal("phase_16_search_favourites_comparison"), favourites: z.array(favouriteSchema), collections: z.array(collectionSchema), collectionItems: z.array(collectionItemSchema), recentQueries: z.array(recentQuerySchema), recentViews: z.array(recentViewSchema), savedComparisons: z.array(savedComparisonSchema), settings: z.array(settingSchema), auditEvents: z.array(auditEventSchema), deletedRecords: z.array(deletedRecordSchema) });
export type EntityReference = z.infer<typeof entityRefSchema>;
export type Favourite = z.infer<typeof favouriteSchema>;
export type SavedCollection = z.infer<typeof collectionSchema>;
export type CollectionItem = z.infer<typeof collectionItemSchema>;
export type RecentQuery = z.infer<typeof recentQuerySchema>;
export type RecentView = z.infer<typeof recentViewSchema>;
export type SavedComparison = z.infer<typeof savedComparisonSchema>;
export type Phase16Backup = z.infer<typeof phase16BackupSchema>;
export const phase16StoreNames = ["phase16Favourites", "phase16Collections", "phase16CollectionItems", "phase16RecentQueries", "phase16RecentViews", "phase16SavedComparisons", "phase16Settings", "phase16AuditEvents", "phase16DeletedRecords", "phase16ImportConflicts", "phase16PrivateSearchCache"] as const;
export type Phase16StoreName = (typeof phase16StoreNames)[number];
