/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CardioRouteImport } from './routes/cardio'
import { Route as DietRouteImport } from './routes/diet'
import { Route as EatRouteImport } from './routes/eat'
import { Route as ExercisesRouteImport } from './routes/exercises'
import { Route as FoodsRouteImport } from './routes/foods'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as MobilityRouteImport } from './routes/mobility'
import { Route as MusclesRouteImport } from './routes/muscles'
import { Route as NutrientsRouteImport } from './routes/nutrients'
import { Route as NutritionLogRouteImport } from './routes/nutrition-log'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SupplementsRouteImport } from './routes/supplements'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TrackRouteImport } from './routes/track'
import { Route as TrainRouteImport } from './routes/train'
import { Route as TrainingScienceRouteImport } from './routes/training-science'
import { Route as WorkoutRouteImport } from './routes/workout'
import { Route as AboutSourcesRouteImport } from './routes/about.sources'
import { Route as ExercisesSlugRouteImport } from './routes/exercises_.$slug'
import { Route as FoodsSlugRouteImport } from './routes/foods_.$slug'
import { Route as FoodsCategoriesRouteImport } from './routes/foods_.categories'
import { Route as FoodsCompareRouteImport } from './routes/foods_.compare'
import { Route as FoodsMethodologyRouteImport } from './routes/foods_.methodology'
import { Route as FoodsSourcesRouteImport } from './routes/foods_.sources'
import { Route as LearnWorkoutScienceRouteImport } from './routes/learn_.workout-science'
import { Route as MusclesSlugRouteImport } from './routes/muscles_.$slug'
import { Route as NutrientsSlugRouteImport } from './routes/nutrients_.$slug'
import { Route as ProgramsSlugRouteImport } from './routes/programs_.$slug'
import { Route as ProgramsCompareRouteImport } from './routes/programs_.compare'
import { Route as ProgramsCurrentRouteImport } from './routes/programs_.current'
import { Route as ProgramsFinderRouteImport } from './routes/programs_.finder'
import { Route as RecipesSlugRouteImport } from './routes/recipes_.$slug'
import { Route as WorkoutHistoryRouteImport } from './routes/workout_.history'
import { Route as WorkoutSettingsRouteImport } from './routes/workout_.settings'
import { Route as FoodsCategoriesCategoryIdRouteImport } from './routes/foods_.categories_.$categoryId'
import { Route as LearnWorkoutScienceSlugRouteImport } from './routes/learn_.workout-science_.$slug'
import { Route as LearnWorkoutScienceGlossaryRouteImport } from './routes/learn_.workout-science_.glossary'
import { Route as LearnWorkoutScienceMethodsRouteImport } from './routes/learn_.workout-science_.methods'
import { Route as WorkoutHistorySessionIdRouteImport } from './routes/workout_.history_.$sessionId'
import { Route as WorkoutSessionSessionIdRouteImport } from './routes/workout_.session.$sessionId'
import { Route as WorkoutSummarySessionIdRouteImport } from './routes/workout_.summary.$sessionId'
import { Route as WorkoutExercisesExerciseIdHistoryRouteImport } from './routes/workout_.exercises.$exerciseId.history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CardioRoute = CardioRouteImport.update({
  id: '/cardio',
  path: '/cardio',
  getParentRoute: () => rootRouteImport,
} as any)
const DietRoute = DietRouteImport.update({
  id: '/diet',
  path: '/diet',
  getParentRoute: () => rootRouteImport,
} as any)
const EatRoute = EatRouteImport.update({
  id: '/eat',
  path: '/eat',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesRoute = ExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsRoute = FoodsRouteImport.update({
  id: '/foods',
  path: '/foods',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const MobilityRoute = MobilityRouteImport.update({
  id: '/mobility',
  path: '/mobility',
  getParentRoute: () => rootRouteImport,
} as any)
const MusclesRoute = MusclesRouteImport.update({
  id: '/muscles',
  path: '/muscles',
  getParentRoute: () => rootRouteImport,
} as any)
const NutrientsRoute = NutrientsRouteImport.update({
  id: '/nutrients',
  path: '/nutrients',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionLogRoute = NutritionLogRouteImport.update({
  id: '/nutrition-log',
  path: '/nutrition-log',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplementsRoute = SupplementsRouteImport.update({
  id: '/supplements',
  path: '/supplements',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainRoute = TrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingScienceRoute = TrainingScienceRouteImport.update({
  id: '/training-science',
  path: '/training-science',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutRoute = WorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutSourcesRoute = AboutSourcesRouteImport.update({
  id: '/about/sources',
  path: '/about/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesSlugRoute = ExercisesSlugRouteImport.update({
  id: '/exercises_/$slug',
  path: '/exercises/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsSlugRoute = FoodsSlugRouteImport.update({
  id: '/foods_/$slug',
  path: '/foods/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsCategoriesRoute = FoodsCategoriesRouteImport.update({
  id: '/foods_/categories',
  path: '/foods/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsCompareRoute = FoodsCompareRouteImport.update({
  id: '/foods_/compare',
  path: '/foods/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsMethodologyRoute = FoodsMethodologyRouteImport.update({
  id: '/foods_/methodology',
  path: '/foods/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsSourcesRoute = FoodsSourcesRouteImport.update({
  id: '/foods_/sources',
  path: '/foods/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnWorkoutScienceRoute = LearnWorkoutScienceRouteImport.update({
  id: '/learn_/workout-science',
  path: '/learn/workout-science',
  getParentRoute: () => rootRouteImport,
} as any)
const MusclesSlugRoute = MusclesSlugRouteImport.update({
  id: '/muscles_/$slug',
  path: '/muscles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NutrientsSlugRoute = NutrientsSlugRouteImport.update({
  id: '/nutrients_/$slug',
  path: '/nutrients/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/programs_/$slug',
  path: '/programs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsCompareRoute = ProgramsCompareRouteImport.update({
  id: '/programs_/compare',
  path: '/programs/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsCurrentRoute = ProgramsCurrentRouteImport.update({
  id: '/programs_/current',
  path: '/programs/current',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsFinderRoute = ProgramsFinderRouteImport.update({
  id: '/programs_/finder',
  path: '/programs/finder',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesSlugRoute = RecipesSlugRouteImport.update({
  id: '/recipes_/$slug',
  path: '/recipes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutHistoryRoute = WorkoutHistoryRouteImport.update({
  id: '/workout_/history',
  path: '/workout/history',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutSettingsRoute = WorkoutSettingsRouteImport.update({
  id: '/workout_/settings',
  path: '/workout/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsCategoriesCategoryIdRoute =
  FoodsCategoriesCategoryIdRouteImport.update({
    id: '/foods_/categories_/$categoryId',
    path: '/foods/categories/$categoryId',
    getParentRoute: () => rootRouteImport,
  } as any)
const LearnWorkoutScienceSlugRoute = LearnWorkoutScienceSlugRouteImport.update({
  id: '/learn_/workout-science_/$slug',
  path: '/learn/workout-science/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnWorkoutScienceGlossaryRoute =
  LearnWorkoutScienceGlossaryRouteImport.update({
    id: '/learn_/workout-science_/glossary',
    path: '/learn/workout-science/glossary',
    getParentRoute: () => rootRouteImport,
  } as any)
const LearnWorkoutScienceMethodsRoute =
  LearnWorkoutScienceMethodsRouteImport.update({
    id: '/learn_/workout-science_/methods',
    path: '/learn/workout-science/methods',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkoutHistorySessionIdRoute = WorkoutHistorySessionIdRouteImport.update({
  id: '/workout_/history_/$sessionId',
  path: '/workout/history/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutSessionSessionIdRoute = WorkoutSessionSessionIdRouteImport.update({
  id: '/workout_/session/$sessionId',
  path: '/workout/session/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutSummarySessionIdRoute = WorkoutSummarySessionIdRouteImport.update({
  id: '/workout_/summary/$sessionId',
  path: '/workout/summary/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutExercisesExerciseIdHistoryRoute =
  WorkoutExercisesExerciseIdHistoryRouteImport.update({
    id: '/workout_/exercises/$exerciseId/history',
    path: '/workout/exercises/$exerciseId/history',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cardio': typeof CardioRoute
  '/diet': typeof DietRoute
  '/eat': typeof EatRoute
  '/exercises': typeof ExercisesRoute
  '/foods': typeof FoodsRoute
  '/learn': typeof LearnRoute
  '/mobility': typeof MobilityRoute
  '/muscles': typeof MusclesRoute
  '/nutrients': typeof NutrientsRoute
  '/nutrition-log': typeof NutritionLogRoute
  '/programs': typeof ProgramsRoute
  '/progress': typeof ProgressRoute
  '/recipes': typeof RecipesRoute
  '/recovery': typeof RecoveryRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/supplements': typeof SupplementsRoute
  '/tools': typeof ToolsRoute
  '/track': typeof TrackRoute
  '/train': typeof TrainRoute
  '/training-science': typeof TrainingScienceRoute
  '/workout': typeof WorkoutRoute
  '/about/sources': typeof AboutSourcesRoute
  '/exercises/$slug': typeof ExercisesSlugRoute
  '/foods/$slug': typeof FoodsSlugRoute
  '/foods/categories': typeof FoodsCategoriesRoute
  '/foods/compare': typeof FoodsCompareRoute
  '/foods/methodology': typeof FoodsMethodologyRoute
  '/foods/sources': typeof FoodsSourcesRoute
  '/learn/workout-science': typeof LearnWorkoutScienceRoute
  '/muscles/$slug': typeof MusclesSlugRoute
  '/nutrients/$slug': typeof NutrientsSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/programs/compare': typeof ProgramsCompareRoute
  '/programs/current': typeof ProgramsCurrentRoute
  '/programs/finder': typeof ProgramsFinderRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/workout/history': typeof WorkoutHistoryRoute
  '/workout/settings': typeof WorkoutSettingsRoute
  '/foods/categories/$categoryId': typeof FoodsCategoriesCategoryIdRoute
  '/learn/workout-science/$slug': typeof LearnWorkoutScienceSlugRoute
  '/learn/workout-science/glossary': typeof LearnWorkoutScienceGlossaryRoute
  '/learn/workout-science/methods': typeof LearnWorkoutScienceMethodsRoute
  '/workout/history/$sessionId': typeof WorkoutHistorySessionIdRoute
  '/workout/session/$sessionId': typeof WorkoutSessionSessionIdRoute
  '/workout/summary/$sessionId': typeof WorkoutSummarySessionIdRoute
  '/workout/exercises/$exerciseId/history': typeof WorkoutExercisesExerciseIdHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cardio': typeof CardioRoute
  '/diet': typeof DietRoute
  '/eat': typeof EatRoute
  '/exercises': typeof ExercisesRoute
  '/foods': typeof FoodsRoute
  '/learn': typeof LearnRoute
  '/mobility': typeof MobilityRoute
  '/muscles': typeof MusclesRoute
  '/nutrients': typeof NutrientsRoute
  '/nutrition-log': typeof NutritionLogRoute
  '/programs': typeof ProgramsRoute
  '/progress': typeof ProgressRoute
  '/recipes': typeof RecipesRoute
  '/recovery': typeof RecoveryRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/supplements': typeof SupplementsRoute
  '/tools': typeof ToolsRoute
  '/track': typeof TrackRoute
  '/train': typeof TrainRoute
  '/training-science': typeof TrainingScienceRoute
  '/workout': typeof WorkoutRoute
  '/about/sources': typeof AboutSourcesRoute
  '/exercises/$slug': typeof ExercisesSlugRoute
  '/foods/$slug': typeof FoodsSlugRoute
  '/foods/categories': typeof FoodsCategoriesRoute
  '/foods/compare': typeof FoodsCompareRoute
  '/foods/methodology': typeof FoodsMethodologyRoute
  '/foods/sources': typeof FoodsSourcesRoute
  '/learn/workout-science': typeof LearnWorkoutScienceRoute
  '/muscles/$slug': typeof MusclesSlugRoute
  '/nutrients/$slug': typeof NutrientsSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/programs/compare': typeof ProgramsCompareRoute
  '/programs/current': typeof ProgramsCurrentRoute
  '/programs/finder': typeof ProgramsFinderRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/workout/history': typeof WorkoutHistoryRoute
  '/workout/settings': typeof WorkoutSettingsRoute
  '/foods/categories/$categoryId': typeof FoodsCategoriesCategoryIdRoute
  '/learn/workout-science/$slug': typeof LearnWorkoutScienceSlugRoute
  '/learn/workout-science/glossary': typeof LearnWorkoutScienceGlossaryRoute
  '/learn/workout-science/methods': typeof LearnWorkoutScienceMethodsRoute
  '/workout/history/$sessionId': typeof WorkoutHistorySessionIdRoute
  '/workout/session/$sessionId': typeof WorkoutSessionSessionIdRoute
  '/workout/summary/$sessionId': typeof WorkoutSummarySessionIdRoute
  '/workout/exercises/$exerciseId/history': typeof WorkoutExercisesExerciseIdHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cardio': typeof CardioRoute
  '/diet': typeof DietRoute
  '/eat': typeof EatRoute
  '/exercises': typeof ExercisesRoute
  '/foods': typeof FoodsRoute
  '/learn': typeof LearnRoute
  '/mobility': typeof MobilityRoute
  '/muscles': typeof MusclesRoute
  '/nutrients': typeof NutrientsRoute
  '/nutrition-log': typeof NutritionLogRoute
  '/programs': typeof ProgramsRoute
  '/progress': typeof ProgressRoute
  '/recipes': typeof RecipesRoute
  '/recovery': typeof RecoveryRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/supplements': typeof SupplementsRoute
  '/tools': typeof ToolsRoute
  '/track': typeof TrackRoute
  '/train': typeof TrainRoute
  '/training-science': typeof TrainingScienceRoute
  '/workout': typeof WorkoutRoute
  '/about/sources': typeof AboutSourcesRoute
  '/exercises_/$slug': typeof ExercisesSlugRoute
  '/foods_/$slug': typeof FoodsSlugRoute
  '/foods_/categories': typeof FoodsCategoriesRoute
  '/foods_/compare': typeof FoodsCompareRoute
  '/foods_/methodology': typeof FoodsMethodologyRoute
  '/foods_/sources': typeof FoodsSourcesRoute
  '/learn_/workout-science': typeof LearnWorkoutScienceRoute
  '/muscles_/$slug': typeof MusclesSlugRoute
  '/nutrients_/$slug': typeof NutrientsSlugRoute
  '/programs_/$slug': typeof ProgramsSlugRoute
  '/programs_/compare': typeof ProgramsCompareRoute
  '/programs_/current': typeof ProgramsCurrentRoute
  '/programs_/finder': typeof ProgramsFinderRoute
  '/recipes_/$slug': typeof RecipesSlugRoute
  '/workout_/history': typeof WorkoutHistoryRoute
  '/workout_/settings': typeof WorkoutSettingsRoute
  '/foods_/categories_/$categoryId': typeof FoodsCategoriesCategoryIdRoute
  '/learn_/workout-science_/$slug': typeof LearnWorkoutScienceSlugRoute
  '/learn_/workout-science_/glossary': typeof LearnWorkoutScienceGlossaryRoute
  '/learn_/workout-science_/methods': typeof LearnWorkoutScienceMethodsRoute
  '/workout_/history_/$sessionId': typeof WorkoutHistorySessionIdRoute
  '/workout_/session/$sessionId': typeof WorkoutSessionSessionIdRoute
  '/workout_/summary/$sessionId': typeof WorkoutSummarySessionIdRoute
  '/workout_/exercises/$exerciseId/history': typeof WorkoutExercisesExerciseIdHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cardio'
    | '/diet'
    | '/eat'
    | '/exercises'
    | '/foods'
    | '/learn'
    | '/mobility'
    | '/muscles'
    | '/nutrients'
    | '/nutrition-log'
    | '/programs'
    | '/progress'
    | '/recipes'
    | '/recovery'
    | '/saved'
    | '/settings'
    | '/supplements'
    | '/tools'
    | '/track'
    | '/train'
    | '/training-science'
    | '/workout'
    | '/about/sources'
    | '/exercises/$slug'
    | '/foods/$slug'
    | '/foods/categories'
    | '/foods/compare'
    | '/foods/methodology'
    | '/foods/sources'
    | '/learn/workout-science'
    | '/muscles/$slug'
    | '/nutrients/$slug'
    | '/programs/$slug'
    | '/programs/compare'
    | '/programs/current'
    | '/programs/finder'
    | '/recipes/$slug'
    | '/workout/history'
    | '/workout/settings'
    | '/foods/categories/$categoryId'
    | '/learn/workout-science/$slug'
    | '/learn/workout-science/glossary'
    | '/learn/workout-science/methods'
    | '/workout/history/$sessionId'
    | '/workout/session/$sessionId'
    | '/workout/summary/$sessionId'
    | '/workout/exercises/$exerciseId/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cardio'
    | '/diet'
    | '/eat'
    | '/exercises'
    | '/foods'
    | '/learn'
    | '/mobility'
    | '/muscles'
    | '/nutrients'
    | '/nutrition-log'
    | '/programs'
    | '/progress'
    | '/recipes'
    | '/recovery'
    | '/saved'
    | '/settings'
    | '/supplements'
    | '/tools'
    | '/track'
    | '/train'
    | '/training-science'
    | '/workout'
    | '/about/sources'
    | '/exercises/$slug'
    | '/foods/$slug'
    | '/foods/categories'
    | '/foods/compare'
    | '/foods/methodology'
    | '/foods/sources'
    | '/learn/workout-science'
    | '/muscles/$slug'
    | '/nutrients/$slug'
    | '/programs/$slug'
    | '/programs/compare'
    | '/programs/current'
    | '/programs/finder'
    | '/recipes/$slug'
    | '/workout/history'
    | '/workout/settings'
    | '/foods/categories/$categoryId'
    | '/learn/workout-science/$slug'
    | '/learn/workout-science/glossary'
    | '/learn/workout-science/methods'
    | '/workout/history/$sessionId'
    | '/workout/session/$sessionId'
    | '/workout/summary/$sessionId'
    | '/workout/exercises/$exerciseId/history'
  id:
    | '__root__'
    | '/'
    | '/cardio'
    | '/diet'
    | '/eat'
    | '/exercises'
    | '/foods'
    | '/learn'
    | '/mobility'
    | '/muscles'
    | '/nutrients'
    | '/nutrition-log'
    | '/programs'
    | '/progress'
    | '/recipes'
    | '/recovery'
    | '/saved'
    | '/settings'
    | '/supplements'
    | '/tools'
    | '/track'
    | '/train'
    | '/training-science'
    | '/workout'
    | '/about/sources'
    | '/exercises_/$slug'
    | '/foods_/$slug'
    | '/foods_/categories'
    | '/foods_/compare'
    | '/foods_/methodology'
    | '/foods_/sources'
    | '/learn_/workout-science'
    | '/muscles_/$slug'
    | '/nutrients_/$slug'
    | '/programs_/$slug'
    | '/programs_/compare'
    | '/programs_/current'
    | '/programs_/finder'
    | '/recipes_/$slug'
    | '/workout_/history'
    | '/workout_/settings'
    | '/foods_/categories_/$categoryId'
    | '/learn_/workout-science_/$slug'
    | '/learn_/workout-science_/glossary'
    | '/learn_/workout-science_/methods'
    | '/workout_/history_/$sessionId'
    | '/workout_/session/$sessionId'
    | '/workout_/summary/$sessionId'
    | '/workout_/exercises/$exerciseId/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardioRoute: typeof CardioRoute
  DietRoute: typeof DietRoute
  EatRoute: typeof EatRoute
  ExercisesRoute: typeof ExercisesRoute
  FoodsRoute: typeof FoodsRoute
  LearnRoute: typeof LearnRoute
  MobilityRoute: typeof MobilityRoute
  MusclesRoute: typeof MusclesRoute
  NutrientsRoute: typeof NutrientsRoute
  NutritionLogRoute: typeof NutritionLogRoute
  ProgramsRoute: typeof ProgramsRoute
  ProgressRoute: typeof ProgressRoute
  RecipesRoute: typeof RecipesRoute
  RecoveryRoute: typeof RecoveryRoute
  SavedRoute: typeof SavedRoute
  SettingsRoute: typeof SettingsRoute
  SupplementsRoute: typeof SupplementsRoute
  ToolsRoute: typeof ToolsRoute
  TrackRoute: typeof TrackRoute
  TrainRoute: typeof TrainRoute
  TrainingScienceRoute: typeof TrainingScienceRoute
  WorkoutRoute: typeof WorkoutRoute
  AboutSourcesRoute: typeof AboutSourcesRoute
  ExercisesSlugRoute: typeof ExercisesSlugRoute
  FoodsSlugRoute: typeof FoodsSlugRoute
  FoodsCategoriesRoute: typeof FoodsCategoriesRoute
  FoodsCompareRoute: typeof FoodsCompareRoute
  FoodsMethodologyRoute: typeof FoodsMethodologyRoute
  FoodsSourcesRoute: typeof FoodsSourcesRoute
  LearnWorkoutScienceRoute: typeof LearnWorkoutScienceRoute
  MusclesSlugRoute: typeof MusclesSlugRoute
  NutrientsSlugRoute: typeof NutrientsSlugRoute
  ProgramsSlugRoute: typeof ProgramsSlugRoute
  ProgramsCompareRoute: typeof ProgramsCompareRoute
  ProgramsCurrentRoute: typeof ProgramsCurrentRoute
  ProgramsFinderRoute: typeof ProgramsFinderRoute
  RecipesSlugRoute: typeof RecipesSlugRoute
  WorkoutHistoryRoute: typeof WorkoutHistoryRoute
  WorkoutSettingsRoute: typeof WorkoutSettingsRoute
  FoodsCategoriesCategoryIdRoute: typeof FoodsCategoriesCategoryIdRoute
  LearnWorkoutScienceSlugRoute: typeof LearnWorkoutScienceSlugRoute
  LearnWorkoutScienceGlossaryRoute: typeof LearnWorkoutScienceGlossaryRoute
  LearnWorkoutScienceMethodsRoute: typeof LearnWorkoutScienceMethodsRoute
  WorkoutHistorySessionIdRoute: typeof WorkoutHistorySessionIdRoute
  WorkoutSessionSessionIdRoute: typeof WorkoutSessionSessionIdRoute
  WorkoutSummarySessionIdRoute: typeof WorkoutSummarySessionIdRoute
  WorkoutExercisesExerciseIdHistoryRoute: typeof WorkoutExercisesExerciseIdHistoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cardio': {
      id: '/cardio'
      path: '/cardio'
      fullPath: '/cardio'
      preLoaderRoute: typeof CardioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diet': {
      id: '/diet'
      path: '/diet'
      fullPath: '/diet'
      preLoaderRoute: typeof DietRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eat': {
      id: '/eat'
      path: '/eat'
      fullPath: '/eat'
      preLoaderRoute: typeof EatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises': {
      id: '/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods': {
      id: '/foods'
      path: '/foods'
      fullPath: '/foods'
      preLoaderRoute: typeof FoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobility': {
      id: '/mobility'
      path: '/mobility'
      fullPath: '/mobility'
      preLoaderRoute: typeof MobilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/muscles': {
      id: '/muscles'
      path: '/muscles'
      fullPath: '/muscles'
      preLoaderRoute: typeof MusclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrients': {
      id: '/nutrients'
      path: '/nutrients'
      fullPath: '/nutrients'
      preLoaderRoute: typeof NutrientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition-log': {
      id: '/nutrition-log'
      path: '/nutrition-log'
      fullPath: '/nutrition-log'
      preLoaderRoute: typeof NutritionLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplements': {
      id: '/supplements'
      path: '/supplements'
      fullPath: '/supplements'
      preLoaderRoute: typeof SupplementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train': {
      id: '/train'
      path: '/train'
      fullPath: '/train'
      preLoaderRoute: typeof TrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training-science': {
      id: '/training-science'
      path: '/training-science'
      fullPath: '/training-science'
      preLoaderRoute: typeof TrainingScienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout': {
      id: '/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof WorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/sources': {
      id: '/about/sources'
      path: '/about/sources'
      fullPath: '/about/sources'
      preLoaderRoute: typeof AboutSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises_/$slug': {
      id: '/exercises_/$slug'
      path: '/exercises/$slug'
      fullPath: '/exercises/$slug'
      preLoaderRoute: typeof ExercisesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods_/$slug': {
      id: '/foods_/$slug'
      path: '/foods/$slug'
      fullPath: '/foods/$slug'
      preLoaderRoute: typeof FoodsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods_/categories': {
      id: '/foods_/categories'
      path: '/foods/categories'
      fullPath: '/foods/categories'
      preLoaderRoute: typeof FoodsCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods_/compare': {
      id: '/foods_/compare'
      path: '/foods/compare'
      fullPath: '/foods/compare'
      preLoaderRoute: typeof FoodsCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods_/methodology': {
      id: '/foods_/methodology'
      path: '/foods/methodology'
      fullPath: '/foods/methodology'
      preLoaderRoute: typeof FoodsMethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods_/sources': {
      id: '/foods_/sources'
      path: '/foods/sources'
      fullPath: '/foods/sources'
      preLoaderRoute: typeof FoodsSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn_/workout-science': {
      id: '/learn_/workout-science'
      path: '/learn/workout-science'
      fullPath: '/learn/workout-science'
      preLoaderRoute: typeof LearnWorkoutScienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/muscles_/$slug': {
      id: '/muscles_/$slug'
      path: '/muscles/$slug'
      fullPath: '/muscles/$slug'
      preLoaderRoute: typeof MusclesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrients_/$slug': {
      id: '/nutrients_/$slug'
      path: '/nutrients/$slug'
      fullPath: '/nutrients/$slug'
      preLoaderRoute: typeof NutrientsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs_/$slug': {
      id: '/programs_/$slug'
      path: '/programs/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs_/compare': {
      id: '/programs_/compare'
      path: '/programs/compare'
      fullPath: '/programs/compare'
      preLoaderRoute: typeof ProgramsCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs_/current': {
      id: '/programs_/current'
      path: '/programs/current'
      fullPath: '/programs/current'
      preLoaderRoute: typeof ProgramsCurrentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs_/finder': {
      id: '/programs_/finder'
      path: '/programs/finder'
      fullPath: '/programs/finder'
      preLoaderRoute: typeof ProgramsFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes_/$slug': {
      id: '/recipes_/$slug'
      path: '/recipes/$slug'
      fullPath: '/recipes/$slug'
      preLoaderRoute: typeof RecipesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout_/history': {
      id: '/workout_/history'
      path: '/workout/history'
      fullPath: '/workout/history'
      preLoaderRoute: typeof WorkoutHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout_/settings': {
      id: '/workout_/settings'
      path: '/workout/settings'
      fullPath: '/workout/settings'
      preLoaderRoute: typeof WorkoutSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods_/categories_/$categoryId': {
      id: '/foods_/categories_/$categoryId'
      path: '/foods/categories/$categoryId'
      fullPath: '/foods/categories/$categoryId'
      preLoaderRoute: typeof FoodsCategoriesCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn_/workout-science_/$slug': {
      id: '/learn_/workout-science_/$slug'
      path: '/learn/workout-science/$slug'
      fullPath: '/learn/workout-science/$slug'
      preLoaderRoute: typeof LearnWorkoutScienceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn_/workout-science_/glossary': {
      id: '/learn_/workout-science_/glossary'
      path: '/learn/workout-science/glossary'
      fullPath: '/learn/workout-science/glossary'
      preLoaderRoute: typeof LearnWorkoutScienceGlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn_/workout-science_/methods': {
      id: '/learn_/workout-science_/methods'
      path: '/learn/workout-science/methods'
      fullPath: '/learn/workout-science/methods'
      preLoaderRoute: typeof LearnWorkoutScienceMethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout_/history_/$sessionId': {
      id: '/workout_/history_/$sessionId'
      path: '/workout/history/$sessionId'
      fullPath: '/workout/history/$sessionId'
      preLoaderRoute: typeof WorkoutHistorySessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout_/session/$sessionId': {
      id: '/workout_/session/$sessionId'
      path: '/workout/session/$sessionId'
      fullPath: '/workout/session/$sessionId'
      preLoaderRoute: typeof WorkoutSessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout_/summary/$sessionId': {
      id: '/workout_/summary/$sessionId'
      path: '/workout/summary/$sessionId'
      fullPath: '/workout/summary/$sessionId'
      preLoaderRoute: typeof WorkoutSummarySessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout_/exercises/$exerciseId/history': {
      id: '/workout_/exercises/$exerciseId/history'
      path: '/workout/exercises/$exerciseId/history'
      fullPath: '/workout/exercises/$exerciseId/history'
      preLoaderRoute: typeof WorkoutExercisesExerciseIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardioRoute: CardioRoute,
  DietRoute: DietRoute,
  EatRoute: EatRoute,
  ExercisesRoute: ExercisesRoute,
  FoodsRoute: FoodsRoute,
  LearnRoute: LearnRoute,
  MobilityRoute: MobilityRoute,
  MusclesRoute: MusclesRoute,
  NutrientsRoute: NutrientsRoute,
  NutritionLogRoute: NutritionLogRoute,
  ProgramsRoute: ProgramsRoute,
  ProgressRoute: ProgressRoute,
  RecipesRoute: RecipesRoute,
  RecoveryRoute: RecoveryRoute,
  SavedRoute: SavedRoute,
  SettingsRoute: SettingsRoute,
  SupplementsRoute: SupplementsRoute,
  ToolsRoute: ToolsRoute,
  TrackRoute: TrackRoute,
  TrainRoute: TrainRoute,
  TrainingScienceRoute: TrainingScienceRoute,
  WorkoutRoute: WorkoutRoute,
  AboutSourcesRoute: AboutSourcesRoute,
  ExercisesSlugRoute: ExercisesSlugRoute,
  FoodsSlugRoute: FoodsSlugRoute,
  FoodsCategoriesRoute: FoodsCategoriesRoute,
  FoodsCompareRoute: FoodsCompareRoute,
  FoodsMethodologyRoute: FoodsMethodologyRoute,
  FoodsSourcesRoute: FoodsSourcesRoute,
  LearnWorkoutScienceRoute: LearnWorkoutScienceRoute,
  MusclesSlugRoute: MusclesSlugRoute,
  NutrientsSlugRoute: NutrientsSlugRoute,
  ProgramsSlugRoute: ProgramsSlugRoute,
  ProgramsCompareRoute: ProgramsCompareRoute,
  ProgramsCurrentRoute: ProgramsCurrentRoute,
  ProgramsFinderRoute: ProgramsFinderRoute,
  RecipesSlugRoute: RecipesSlugRoute,
  WorkoutHistoryRoute: WorkoutHistoryRoute,
  WorkoutSettingsRoute: WorkoutSettingsRoute,
  FoodsCategoriesCategoryIdRoute: FoodsCategoriesCategoryIdRoute,
  LearnWorkoutScienceSlugRoute: LearnWorkoutScienceSlugRoute,
  LearnWorkoutScienceGlossaryRoute: LearnWorkoutScienceGlossaryRoute,
  LearnWorkoutScienceMethodsRoute: LearnWorkoutScienceMethodsRoute,
  WorkoutHistorySessionIdRoute: WorkoutHistorySessionIdRoute,
  WorkoutSessionSessionIdRoute: WorkoutSessionSessionIdRoute,
  WorkoutSummarySessionIdRoute: WorkoutSummarySessionIdRoute,
  WorkoutExercisesExerciseIdHistoryRoute:
    WorkoutExercisesExerciseIdHistoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
