/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CardioRouteImport } from './routes/cardio'
import { Route as DietRouteImport } from './routes/diet'
import { Route as EatRouteImport } from './routes/eat'
import { Route as ExercisesRouteImport } from './routes/exercises'
import { Route as FoodsRouteImport } from './routes/foods'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as MobilityRouteImport } from './routes/mobility'
import { Route as MusclesRouteImport } from './routes/muscles'
import { Route as NutrientsRouteImport } from './routes/nutrients'
import { Route as NutritionLogRouteImport } from './routes/nutrition-log'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SupplementsRouteImport } from './routes/supplements'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TrackRouteImport } from './routes/track'
import { Route as TrainRouteImport } from './routes/train'
import { Route as TrainingScienceRouteImport } from './routes/training-science'
import { Route as WorkoutRouteImport } from './routes/workout'
import { Route as AboutSourcesRouteImport } from './routes/about.sources'
import { Route as ExercisesSlugRouteImport } from './routes/exercises_.$slug'
import { Route as FoodsSlugRouteImport } from './routes/foods_.$slug'
import { Route as MusclesSlugRouteImport } from './routes/muscles_.$slug'
import { Route as NutrientsSlugRouteImport } from './routes/nutrients_.$slug'
import { Route as ProgramsSlugRouteImport } from './routes/programs_.$slug'
import { Route as RecipesSlugRouteImport } from './routes/recipes_.$slug'
import { Route as WorkoutHistoryRouteImport } from './routes/workout_.history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CardioRoute = CardioRouteImport.update({
  id: '/cardio',
  path: '/cardio',
  getParentRoute: () => rootRouteImport,
} as any)
const DietRoute = DietRouteImport.update({
  id: '/diet',
  path: '/diet',
  getParentRoute: () => rootRouteImport,
} as any)
const EatRoute = EatRouteImport.update({
  id: '/eat',
  path: '/eat',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesRoute = ExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsRoute = FoodsRouteImport.update({
  id: '/foods',
  path: '/foods',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const MobilityRoute = MobilityRouteImport.update({
  id: '/mobility',
  path: '/mobility',
  getParentRoute: () => rootRouteImport,
} as any)
const MusclesRoute = MusclesRouteImport.update({
  id: '/muscles',
  path: '/muscles',
  getParentRoute: () => rootRouteImport,
} as any)
const NutrientsRoute = NutrientsRouteImport.update({
  id: '/nutrients',
  path: '/nutrients',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionLogRoute = NutritionLogRouteImport.update({
  id: '/nutrition-log',
  path: '/nutrition-log',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplementsRoute = SupplementsRouteImport.update({
  id: '/supplements',
  path: '/supplements',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainRoute = TrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingScienceRoute = TrainingScienceRouteImport.update({
  id: '/training-science',
  path: '/training-science',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutRoute = WorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutSourcesRoute = AboutSourcesRouteImport.update({
  id: '/about/sources',
  path: '/about/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesSlugRoute = ExercisesSlugRouteImport.update({
  id: '/exercises_/$slug',
  path: '/exercises/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsSlugRoute = FoodsSlugRouteImport.update({
  id: '/foods_/$slug',
  path: '/foods/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MusclesSlugRoute = MusclesSlugRouteImport.update({
  id: '/muscles_/$slug',
  path: '/muscles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NutrientsSlugRoute = NutrientsSlugRouteImport.update({
  id: '/nutrients_/$slug',
  path: '/nutrients/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/programs_/$slug',
  path: '/programs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesSlugRoute = RecipesSlugRouteImport.update({
  id: '/recipes_/$slug',
  path: '/recipes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutHistoryRoute = WorkoutHistoryRouteImport.update({
  id: '/workout_/history',
  path: '/workout/history',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cardio': typeof CardioRoute
  '/diet': typeof DietRoute
  '/eat': typeof EatRoute
  '/exercises': typeof ExercisesRoute
  '/foods': typeof FoodsRoute
  '/learn': typeof LearnRoute
  '/mobility': typeof MobilityRoute
  '/muscles': typeof MusclesRoute
  '/nutrients': typeof NutrientsRoute
  '/nutrition-log': typeof NutritionLogRoute
  '/programs': typeof ProgramsRoute
  '/progress': typeof ProgressRoute
  '/recipes': typeof RecipesRoute
  '/recovery': typeof RecoveryRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/supplements': typeof SupplementsRoute
  '/tools': typeof ToolsRoute
  '/track': typeof TrackRoute
  '/train': typeof TrainRoute
  '/training-science': typeof TrainingScienceRoute
  '/workout': typeof WorkoutRoute
  '/about/sources': typeof AboutSourcesRoute
  '/exercises/$slug': typeof ExercisesSlugRoute
  '/foods/$slug': typeof FoodsSlugRoute
  '/muscles/$slug': typeof MusclesSlugRoute
  '/nutrients/$slug': typeof NutrientsSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/workout/history': typeof WorkoutHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cardio': typeof CardioRoute
  '/diet': typeof DietRoute
  '/eat': typeof EatRoute
  '/exercises': typeof ExercisesRoute
  '/foods': typeof FoodsRoute
  '/learn': typeof LearnRoute
  '/mobility': typeof MobilityRoute
  '/muscles': typeof MusclesRoute
  '/nutrients': typeof NutrientsRoute
  '/nutrition-log': typeof NutritionLogRoute
  '/programs': typeof ProgramsRoute
  '/progress': typeof ProgressRoute
  '/recipes': typeof RecipesRoute
  '/recovery': typeof RecoveryRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/supplements': typeof SupplementsRoute
  '/tools': typeof ToolsRoute
  '/track': typeof TrackRoute
  '/train': typeof TrainRoute
  '/training-science': typeof TrainingScienceRoute
  '/workout': typeof WorkoutRoute
  '/about/sources': typeof AboutSourcesRoute
  '/exercises/$slug': typeof ExercisesSlugRoute
  '/foods/$slug': typeof FoodsSlugRoute
  '/muscles/$slug': typeof MusclesSlugRoute
  '/nutrients/$slug': typeof NutrientsSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/workout/history': typeof WorkoutHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cardio': typeof CardioRoute
  '/diet': typeof DietRoute
  '/eat': typeof EatRoute
  '/exercises': typeof ExercisesRoute
  '/foods': typeof FoodsRoute
  '/learn': typeof LearnRoute
  '/mobility': typeof MobilityRoute
  '/muscles': typeof MusclesRoute
  '/nutrients': typeof NutrientsRoute
  '/nutrition-log': typeof NutritionLogRoute
  '/programs': typeof ProgramsRoute
  '/progress': typeof ProgressRoute
  '/recipes': typeof RecipesRoute
  '/recovery': typeof RecoveryRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/supplements': typeof SupplementsRoute
  '/tools': typeof ToolsRoute
  '/track': typeof TrackRoute
  '/train': typeof TrainRoute
  '/training-science': typeof TrainingScienceRoute
  '/workout': typeof WorkoutRoute
  '/about/sources': typeof AboutSourcesRoute
  '/exercises_/$slug': typeof ExercisesSlugRoute
  '/foods_/$slug': typeof FoodsSlugRoute
  '/muscles_/$slug': typeof MusclesSlugRoute
  '/nutrients_/$slug': typeof NutrientsSlugRoute
  '/programs_/$slug': typeof ProgramsSlugRoute
  '/recipes_/$slug': typeof RecipesSlugRoute
  '/workout_/history': typeof WorkoutHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cardio'
    | '/diet'
    | '/eat'
    | '/exercises'
    | '/foods'
    | '/learn'
    | '/mobility'
    | '/muscles'
    | '/nutrients'
    | '/nutrition-log'
    | '/programs'
    | '/progress'
    | '/recipes'
    | '/recovery'
    | '/saved'
    | '/settings'
    | '/supplements'
    | '/tools'
    | '/track'
    | '/train'
    | '/training-science'
    | '/workout'
    | '/about/sources'
    | '/exercises/$slug'
    | '/foods/$slug'
    | '/muscles/$slug'
    | '/nutrients/$slug'
    | '/programs/$slug'
    | '/recipes/$slug'
    | '/workout/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cardio'
    | '/diet'
    | '/eat'
    | '/exercises'
    | '/foods'
    | '/learn'
    | '/mobility'
    | '/muscles'
    | '/nutrients'
    | '/nutrition-log'
    | '/programs'
    | '/progress'
    | '/recipes'
    | '/recovery'
    | '/saved'
    | '/settings'
    | '/supplements'
    | '/tools'
    | '/track'
    | '/train'
    | '/training-science'
    | '/workout'
    | '/about/sources'
    | '/exercises/$slug'
    | '/foods/$slug'
    | '/muscles/$slug'
    | '/nutrients/$slug'
    | '/programs/$slug'
    | '/recipes/$slug'
    | '/workout/history'
  id:
    | '__root__'
    | '/'
    | '/cardio'
    | '/diet'
    | '/eat'
    | '/exercises'
    | '/foods'
    | '/learn'
    | '/mobility'
    | '/muscles'
    | '/nutrients'
    | '/nutrition-log'
    | '/programs'
    | '/progress'
    | '/recipes'
    | '/recovery'
    | '/saved'
    | '/settings'
    | '/supplements'
    | '/tools'
    | '/track'
    | '/train'
    | '/training-science'
    | '/workout'
    | '/about/sources'
    | '/exercises_/$slug'
    | '/foods_/$slug'
    | '/muscles_/$slug'
    | '/nutrients_/$slug'
    | '/programs_/$slug'
    | '/recipes_/$slug'
    | '/workout_/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardioRoute: typeof CardioRoute
  DietRoute: typeof DietRoute
  EatRoute: typeof EatRoute
  ExercisesRoute: typeof ExercisesRoute
  FoodsRoute: typeof FoodsRoute
  LearnRoute: typeof LearnRoute
  MobilityRoute: typeof MobilityRoute
  MusclesRoute: typeof MusclesRoute
  NutrientsRoute: typeof NutrientsRoute
  NutritionLogRoute: typeof NutritionLogRoute
  ProgramsRoute: typeof ProgramsRoute
  ProgressRoute: typeof ProgressRoute
  RecipesRoute: typeof RecipesRoute
  RecoveryRoute: typeof RecoveryRoute
  SavedRoute: typeof SavedRoute
  SettingsRoute: typeof SettingsRoute
  SupplementsRoute: typeof SupplementsRoute
  ToolsRoute: typeof ToolsRoute
  TrackRoute: typeof TrackRoute
  TrainRoute: typeof TrainRoute
  TrainingScienceRoute: typeof TrainingScienceRoute
  WorkoutRoute: typeof WorkoutRoute
  AboutSourcesRoute: typeof AboutSourcesRoute
  ExercisesSlugRoute: typeof ExercisesSlugRoute
  FoodsSlugRoute: typeof FoodsSlugRoute
  MusclesSlugRoute: typeof MusclesSlugRoute
  NutrientsSlugRoute: typeof NutrientsSlugRoute
  ProgramsSlugRoute: typeof ProgramsSlugRoute
  RecipesSlugRoute: typeof RecipesSlugRoute
  WorkoutHistoryRoute: typeof WorkoutHistoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cardio': {
      id: '/cardio'
      path: '/cardio'
      fullPath: '/cardio'
      preLoaderRoute: typeof CardioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diet': {
      id: '/diet'
      path: '/diet'
      fullPath: '/diet'
      preLoaderRoute: typeof DietRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eat': {
      id: '/eat'
      path: '/eat'
      fullPath: '/eat'
      preLoaderRoute: typeof EatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises': {
      id: '/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods': {
      id: '/foods'
      path: '/foods'
      fullPath: '/foods'
      preLoaderRoute: typeof FoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobility': {
      id: '/mobility'
      path: '/mobility'
      fullPath: '/mobility'
      preLoaderRoute: typeof MobilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/muscles': {
      id: '/muscles'
      path: '/muscles'
      fullPath: '/muscles'
      preLoaderRoute: typeof MusclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrients': {
      id: '/nutrients'
      path: '/nutrients'
      fullPath: '/nutrients'
      preLoaderRoute: typeof NutrientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition-log': {
      id: '/nutrition-log'
      path: '/nutrition-log'
      fullPath: '/nutrition-log'
      preLoaderRoute: typeof NutritionLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplements': {
      id: '/supplements'
      path: '/supplements'
      fullPath: '/supplements'
      preLoaderRoute: typeof SupplementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train': {
      id: '/train'
      path: '/train'
      fullPath: '/train'
      preLoaderRoute: typeof TrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training-science': {
      id: '/training-science'
      path: '/training-science'
      fullPath: '/training-science'
      preLoaderRoute: typeof TrainingScienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout': {
      id: '/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof WorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/sources': {
      id: '/about/sources'
      path: '/about/sources'
      fullPath: '/about/sources'
      preLoaderRoute: typeof AboutSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises_/$slug': {
      id: '/exercises_/$slug'
      path: '/exercises/$slug'
      fullPath: '/exercises/$slug'
      preLoaderRoute: typeof ExercisesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods_/$slug': {
      id: '/foods_/$slug'
      path: '/foods/$slug'
      fullPath: '/foods/$slug'
      preLoaderRoute: typeof FoodsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/muscles_/$slug': {
      id: '/muscles_/$slug'
      path: '/muscles/$slug'
      fullPath: '/muscles/$slug'
      preLoaderRoute: typeof MusclesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrients_/$slug': {
      id: '/nutrients_/$slug'
      path: '/nutrients/$slug'
      fullPath: '/nutrients/$slug'
      preLoaderRoute: typeof NutrientsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs_/$slug': {
      id: '/programs_/$slug'
      path: '/programs/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes_/$slug': {
      id: '/recipes_/$slug'
      path: '/recipes/$slug'
      fullPath: '/recipes/$slug'
      preLoaderRoute: typeof RecipesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout_/history': {
      id: '/workout_/history'
      path: '/workout/history'
      fullPath: '/workout/history'
      preLoaderRoute: typeof WorkoutHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardioRoute: CardioRoute,
  DietRoute: DietRoute,
  EatRoute: EatRoute,
  ExercisesRoute: ExercisesRoute,
  FoodsRoute: FoodsRoute,
  LearnRoute: LearnRoute,
  MobilityRoute: MobilityRoute,
  MusclesRoute: MusclesRoute,
  NutrientsRoute: NutrientsRoute,
  NutritionLogRoute: NutritionLogRoute,
  ProgramsRoute: ProgramsRoute,
  ProgressRoute: ProgressRoute,
  RecipesRoute: RecipesRoute,
  RecoveryRoute: RecoveryRoute,
  SavedRoute: SavedRoute,
  SettingsRoute: SettingsRoute,
  SupplementsRoute: SupplementsRoute,
  ToolsRoute: ToolsRoute,
  TrackRoute: TrackRoute,
  TrainRoute: TrainRoute,
  TrainingScienceRoute: TrainingScienceRoute,
  WorkoutRoute: WorkoutRoute,
  AboutSourcesRoute: AboutSourcesRoute,
  ExercisesSlugRoute: ExercisesSlugRoute,
  FoodsSlugRoute: FoodsSlugRoute,
  MusclesSlugRoute: MusclesSlugRoute,
  NutrientsSlugRoute: NutrientsSlugRoute,
  ProgramsSlugRoute: ProgramsSlugRoute,
  RecipesSlugRoute: RecipesSlugRoute,
  WorkoutHistoryRoute: WorkoutHistoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
