/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CardioRouteImport } from './routes/cardio'
import { Route as DietRouteImport } from './routes/diet'
import { Route as DietPlanningRouteImport } from './routes/diet-planning'
import { Route as EatRouteImport } from './routes/eat'
import { Route as ExercisesRouteImport } from './routes/exercises'
import { Route as FoodsRouteImport } from './routes/foods'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as MobilityRouteImport } from './routes/mobility'
import { Route as MusclesRouteImport } from './routes/muscles'
import { Route as NutrientsRouteImport } from './routes/nutrients'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as NutritionLogRouteImport } from './routes/nutrition-log'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SupplementsRouteImport } from './routes/supplements'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TrackRouteImport } from './routes/track'
import { Route as TrainRouteImport } from './routes/train'
import { Route as TrainingScienceRouteImport } from './routes/training-science'
import { Route as WorkoutRouteImport } from './routes/workout'
import { Route as AboutSourcesRouteImport } from './routes/about.sources'
import { Route as DietPlanningIndexRouteImport } from './routes/diet-planning.index'
import { Route as DietPlanningEnergyRouteImport } from './routes/diet-planning.energy'
import { Route as DietPlanningGoalRouteImport } from './routes/diet-planning.goal'
import { Route as DietPlanningMacrosRouteImport } from './routes/diet-planning.macros'
import { Route as DietPlanningMealDistributionRouteImport } from './routes/diet-planning.meal-distribution'
import { Route as DietPlanningMethodologyRouteImport } from './routes/diet-planning.methodology'
import { Route as DietPlanningPlansRouteImport } from './routes/diet-planning.plans'
import { Route as DietPlanningSafetyRouteImport } from './routes/diet-planning.safety'
import { Route as ExercisesSlugRouteImport } from './routes/exercises_.$slug'
import { Route as FoodsSlugRouteImport } from './routes/foods_.$slug'
import { Route as FoodsCategoriesRouteImport } from './routes/foods_.categories'
import { Route as FoodsCompareRouteImport } from './routes/foods_.compare'
import { Route as FoodsMethodologyRouteImport } from './routes/foods_.methodology'
import { Route as FoodsSourcesRouteImport } from './routes/foods_.sources'
import { Route as LearnWorkoutScienceRouteImport } from './routes/learn_.workout-science'
import { Route as MusclesSlugRouteImport } from './routes/muscles_.$slug'
import { Route as NutrientsSlugRouteImport } from './routes/nutrients_.$slug'
import { Route as NutrientsCompareRouteImport } from './routes/nutrients_.compare'
import { Route as NutrientsFrameworksRouteImport } from './routes/nutrients_.frameworks'
import { Route as NutrientsGlossaryRouteImport } from './routes/nutrients_.glossary'
import { Route as NutrientsMethodologyRouteImport } from './routes/nutrients_.methodology'
import { Route as NutrientsReferenceIntakesRouteImport } from './routes/nutrients_.reference-intakes'
import { Route as NutritionIndexRouteImport } from './routes/nutrition.index'
import { Route as NutritionAddRouteImport } from './routes/nutrition.add'
import { Route as NutritionCustomFoodsRouteImport } from './routes/nutrition.custom-foods'
import { Route as NutritionDayRouteImport } from './routes/nutrition.day'
import { Route as NutritionHistoryRouteImport } from './routes/nutrition.history'
import { Route as NutritionMethodologyRouteImport } from './routes/nutrition.methodology'
import { Route as NutritionPrivacyRouteImport } from './routes/nutrition.privacy'
import { Route as NutritionSettingsRouteImport } from './routes/nutrition.settings'
import { Route as ProgramsSlugRouteImport } from './routes/programs_.$slug'
import { Route as ProgramsCompareRouteImport } from './routes/programs_.compare'
import { Route as ProgramsCurrentRouteImport } from './routes/programs_.current'
import { Route as ProgramsFinderRouteImport } from './routes/programs_.finder'
import { Route as RecipesSlugRouteImport } from './routes/recipes_.$slug'
import { Route as WorkoutHistoryRouteImport } from './routes/workout_.history'
import { Route as WorkoutSettingsRouteImport } from './routes/workout_.settings'
import { Route as DietPlanningPlansIndexRouteImport } from './routes/diet-planning.plans.index'
import { Route as DietPlanningPlansPlanIdRouteImport } from './routes/diet-planning.plans.$planId'
import { Route as FoodsCategoriesCategoryIdRouteImport } from './routes/foods_.categories_.$categoryId'
import { Route as LearnWorkoutScienceSlugRouteImport } from './routes/learn_.workout-science_.$slug'
import { Route as LearnWorkoutScienceGlossaryRouteImport } from './routes/learn_.workout-science_.glossary'
import { Route as LearnWorkoutScienceMethodsRouteImport } from './routes/learn_.workout-science_.methods'
import { Route as NutrientsCategoriesGroupIdRouteImport } from './routes/nutrients_.categories_.$groupId'
import { Route as NutritionCustomFoodsIndexRouteImport } from './routes/nutrition.custom-foods.index'
import { Route as NutritionCustomFoodsCustomFoodIdRouteImport } from './routes/nutrition.custom-foods.$customFoodId'
import { Route as NutritionDayDateRouteImport } from './routes/nutrition.day.$date'
import { Route as WorkoutHistorySessionIdRouteImport } from './routes/workout_.history_.$sessionId'
import { Route as WorkoutSessionSessionIdRouteImport } from './routes/workout_.session.$sessionId'
import { Route as WorkoutSummarySessionIdRouteImport } from './routes/workout_.summary.$sessionId'
import { Route as WorkoutExercisesExerciseIdHistoryRouteImport } from './routes/workout_.exercises.$exerciseId.history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CardioRoute = CardioRouteImport.update({
  id: '/cardio',
  path: '/cardio',
  getParentRoute: () => rootRouteImport,
} as any)
const DietRoute = DietRouteImport.update({
  id: '/diet',
  path: '/diet',
  getParentRoute: () => rootRouteImport,
} as any)
const DietPlanningRoute = DietPlanningRouteImport.update({
  id: '/diet-planning',
  path: '/diet-planning',
  getParentRoute: () => rootRouteImport,
} as any)
const EatRoute = EatRouteImport.update({
  id: '/eat',
  path: '/eat',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesRoute = ExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsRoute = FoodsRouteImport.update({
  id: '/foods',
  path: '/foods',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const MobilityRoute = MobilityRouteImport.update({
  id: '/mobility',
  path: '/mobility',
  getParentRoute: () => rootRouteImport,
} as any)
const MusclesRoute = MusclesRouteImport.update({
  id: '/muscles',
  path: '/muscles',
  getParentRoute: () => rootRouteImport,
} as any)
const NutrientsRoute = NutrientsRouteImport.update({
  id: '/nutrients',
  path: '/nutrients',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionLogRoute = NutritionLogRouteImport.update({
  id: '/nutrition-log',
  path: '/nutrition-log',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplementsRoute = SupplementsRouteImport.update({
  id: '/supplements',
  path: '/supplements',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainRoute = TrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingScienceRoute = TrainingScienceRouteImport.update({
  id: '/training-science',
  path: '/training-science',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutRoute = WorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutSourcesRoute = AboutSourcesRouteImport.update({
  id: '/about/sources',
  path: '/about/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const DietPlanningIndexRoute = DietPlanningIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DietPlanningRoute,
} as any)
const DietPlanningEnergyRoute = DietPlanningEnergyRouteImport.update({
  id: '/energy',
  path: '/energy',
  getParentRoute: () => DietPlanningRoute,
} as any)
const DietPlanningGoalRoute = DietPlanningGoalRouteImport.update({
  id: '/goal',
  path: '/goal',
  getParentRoute: () => DietPlanningRoute,
} as any)
const DietPlanningMacrosRoute = DietPlanningMacrosRouteImport.update({
  id: '/macros',
  path: '/macros',
  getParentRoute: () => DietPlanningRoute,
} as any)
const DietPlanningMealDistributionRoute =
  DietPlanningMealDistributionRouteImport.update({
    id: '/meal-distribution',
    path: '/meal-distribution',
    getParentRoute: () => DietPlanningRoute,
  } as any)
const DietPlanningMethodologyRoute = DietPlanningMethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => DietPlanningRoute,
} as any)
const DietPlanningPlansRoute = DietPlanningPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => DietPlanningRoute,
} as any)
const DietPlanningSafetyRoute = DietPlanningSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => DietPlanningRoute,
} as any)
const ExercisesSlugRoute = ExercisesSlugRouteImport.update({
  id: '/exercises_/$slug',
  path: '/exercises/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsSlugRoute = FoodsSlugRouteImport.update({
  id: '/foods_/$slug',
  path: '/foods/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsCategoriesRoute = FoodsCategoriesRouteImport.update({
  id: '/foods_/categories',
  path: '/foods/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsCompareRoute = FoodsCompareRouteImport.update({
  id: '/foods_/compare',
  path: '/foods/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsMethodologyRoute = FoodsMethodologyRouteImport.update({
  id: '/foods_/methodology',
  path: '/foods/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsSourcesRoute = FoodsSourcesRouteImport.update({
  id: '/foods_/sources',
  path: '/foods/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnWorkoutScienceRoute = LearnWorkoutScienceRouteImport.update({
  id: '/learn_/workout-science',
  path: '/learn/workout-science',
  getParentRoute: () => rootRouteImport,
} as any)
const MusclesSlugRoute = MusclesSlugRouteImport.update({
  id: '/muscles_/$slug',
  path: '/muscles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NutrientsSlugRoute = NutrientsSlugRouteImport.update({
  id: '/nutrients_/$slug',
  path: '/nutrients/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NutrientsCompareRoute = NutrientsCompareRouteImport.update({
  id: '/nutrients_/compare',
  path: '/nutrients/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const NutrientsFrameworksRoute = NutrientsFrameworksRouteImport.update({
  id: '/nutrients_/frameworks',
  path: '/nutrients/frameworks',
  getParentRoute: () => rootRouteImport,
} as any)
const NutrientsGlossaryRoute = NutrientsGlossaryRouteImport.update({
  id: '/nutrients_/glossary',
  path: '/nutrients/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const NutrientsMethodologyRoute = NutrientsMethodologyRouteImport.update({
  id: '/nutrients_/methodology',
  path: '/nutrients/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const NutrientsReferenceIntakesRoute =
  NutrientsReferenceIntakesRouteImport.update({
    id: '/nutrients_/reference-intakes',
    path: '/nutrients/reference-intakes',
    getParentRoute: () => rootRouteImport,
  } as any)
const NutritionIndexRoute = NutritionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NutritionRoute,
} as any)
const NutritionAddRoute = NutritionAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => NutritionRoute,
} as any)
const NutritionCustomFoodsRoute = NutritionCustomFoodsRouteImport.update({
  id: '/custom-foods',
  path: '/custom-foods',
  getParentRoute: () => NutritionRoute,
} as any)
const NutritionDayRoute = NutritionDayRouteImport.update({
  id: '/day',
  path: '/day',
  getParentRoute: () => NutritionRoute,
} as any)
const NutritionHistoryRoute = NutritionHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => NutritionRoute,
} as any)
const NutritionMethodologyRoute = NutritionMethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => NutritionRoute,
} as any)
const NutritionPrivacyRoute = NutritionPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => NutritionRoute,
} as any)
const NutritionSettingsRoute = NutritionSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => NutritionRoute,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/programs_/$slug',
  path: '/programs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsCompareRoute = ProgramsCompareRouteImport.update({
  id: '/programs_/compare',
  path: '/programs/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsCurrentRoute = ProgramsCurrentRouteImport.update({
  id: '/programs_/current',
  path: '/programs/current',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsFinderRoute = ProgramsFinderRouteImport.update({
  id: '/programs_/finder',
  path: '/programs/finder',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesSlugRoute = RecipesSlugRouteImport.update({
  id: '/recipes_/$slug',
  path: '/recipes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutHistoryRoute = WorkoutHistoryRouteImport.update({
  id: '/workout_/history',
  path: '/workout/history',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutSettingsRoute = WorkoutSettingsRouteImport.update({
  id: '/workout_/settings',
  path: '/workout/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DietPlanningPlansIndexRoute = DietPlanningPlansIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DietPlanningPlansRoute,
} as any)
const DietPlanningPlansPlanIdRoute = DietPlanningPlansPlanIdRouteImport.update({
  id: '/$planId',
  path: '/$planId',
  getParentRoute: () => DietPlanningPlansRoute,
} as any)
const FoodsCategoriesCategoryIdRoute =
  FoodsCategoriesCategoryIdRouteImport.update({
    id: '/foods_/categories_/$categoryId',
    path: '/foods/categories/$categoryId',
    getParentRoute: () => rootRouteImport,
  } as any)
const LearnWorkoutScienceSlugRoute = LearnWorkoutScienceSlugRouteImport.update({
  id: '/learn_/workout-science_/$slug',
  path: '/learn/workout-science/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnWorkoutScienceGlossaryRoute =
  LearnWorkoutScienceGlossaryRouteImport.update({
    id: '/learn_/workout-science_/glossary',
    path: '/learn/workout-science/glossary',
    getParentRoute: () => rootRouteImport,
  } as any)
const LearnWorkoutScienceMethodsRoute =
  LearnWorkoutScienceMethodsRouteImport.update({
    id: '/learn_/workout-science_/methods',
    path: '/learn/workout-science/methods',
    getParentRoute: () => rootRouteImport,
  } as any)
const NutrientsCategoriesGroupIdRoute =
  NutrientsCategoriesGroupIdRouteImport.update({
    id: '/nutrients_/categories_/$groupId',
    path: '/nutrients/categories/$groupId',
    getParentRoute: () => rootRouteImport,
  } as any)
const NutritionCustomFoodsIndexRoute =
  NutritionCustomFoodsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => NutritionCustomFoodsRoute,
  } as any)
const NutritionCustomFoodsCustomFoodIdRoute =
  NutritionCustomFoodsCustomFoodIdRouteImport.update({
    id: '/$customFoodId',
    path: '/$customFoodId',
    getParentRoute: () => NutritionCustomFoodsRoute,
  } as any)
const NutritionDayDateRoute = NutritionDayDateRouteImport.update({
  id: '/$date',
  path: '/$date',
  getParentRoute: () => NutritionDayRoute,
} as any)
const WorkoutHistorySessionIdRoute = WorkoutHistorySessionIdRouteImport.update({
  id: '/workout_/history_/$sessionId',
  path: '/workout/history/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutSessionSessionIdRoute = WorkoutSessionSessionIdRouteImport.update({
  id: '/workout_/session/$sessionId',
  path: '/workout/session/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutSummarySessionIdRoute = WorkoutSummarySessionIdRouteImport.update({
  id: '/workout_/summary/$sessionId',
  path: '/workout/summary/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutExercisesExerciseIdHistoryRoute =
  WorkoutExercisesExerciseIdHistoryRouteImport.update({
    id: '/workout_/exercises/$exerciseId/history',
    path: '/workout/exercises/$exerciseId/history',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cardio': typeof CardioRoute
  '/diet': typeof DietRoute
  '/diet-planning': typeof DietPlanningRouteWithChildren
  '/eat': typeof EatRoute
  '/exercises': typeof ExercisesRoute
  '/foods': typeof FoodsRoute
  '/learn': typeof LearnRoute
  '/mobility': typeof MobilityRoute
  '/muscles': typeof MusclesRoute
  '/nutrients': typeof NutrientsRoute
  '/nutrition': typeof NutritionRouteWithChildren
  '/nutrition-log': typeof NutritionLogRoute
  '/programs': typeof ProgramsRoute
  '/progress': typeof ProgressRoute
  '/recipes': typeof RecipesRoute
  '/recovery': typeof RecoveryRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/supplements': typeof SupplementsRoute
  '/tools': typeof ToolsRoute
  '/track': typeof TrackRoute
  '/train': typeof TrainRoute
  '/training-science': typeof TrainingScienceRoute
  '/workout': typeof WorkoutRoute
  '/about/sources': typeof AboutSourcesRoute
  '/diet-planning/energy': typeof DietPlanningEnergyRoute
  '/diet-planning/goal': typeof DietPlanningGoalRoute
  '/diet-planning/macros': typeof DietPlanningMacrosRoute
  '/diet-planning/meal-distribution': typeof DietPlanningMealDistributionRoute
  '/diet-planning/methodology': typeof DietPlanningMethodologyRoute
  '/diet-planning/plans': typeof DietPlanningPlansRouteWithChildren
  '/diet-planning/safety': typeof DietPlanningSafetyRoute
  '/exercises/$slug': typeof ExercisesSlugRoute
  '/foods/$slug': typeof FoodsSlugRoute
  '/foods/categories': typeof FoodsCategoriesRoute
  '/foods/compare': typeof FoodsCompareRoute
  '/foods/methodology': typeof FoodsMethodologyRoute
  '/foods/sources': typeof FoodsSourcesRoute
  '/learn/workout-science': typeof LearnWorkoutScienceRoute
  '/muscles/$slug': typeof MusclesSlugRoute
  '/nutrients/$slug': typeof NutrientsSlugRoute
  '/nutrients/compare': typeof NutrientsCompareRoute
  '/nutrients/frameworks': typeof NutrientsFrameworksRoute
  '/nutrients/glossary': typeof NutrientsGlossaryRoute
  '/nutrients/methodology': typeof NutrientsMethodologyRoute
  '/nutrients/reference-intakes': typeof NutrientsReferenceIntakesRoute
  '/nutrition/add': typeof NutritionAddRoute
  '/nutrition/custom-foods': typeof NutritionCustomFoodsRouteWithChildren
  '/nutrition/day': typeof NutritionDayRouteWithChildren
  '/nutrition/history': typeof NutritionHistoryRoute
  '/nutrition/methodology': typeof NutritionMethodologyRoute
  '/nutrition/privacy': typeof NutritionPrivacyRoute
  '/nutrition/settings': typeof NutritionSettingsRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/programs/compare': typeof ProgramsCompareRoute
  '/programs/current': typeof ProgramsCurrentRoute
  '/programs/finder': typeof ProgramsFinderRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/workout/history': typeof WorkoutHistoryRoute
  '/workout/settings': typeof WorkoutSettingsRoute
  '/diet-planning/': typeof DietPlanningIndexRoute
  '/nutrition/': typeof NutritionIndexRoute
  '/diet-planning/plans/$planId': typeof DietPlanningPlansPlanIdRoute
  '/foods/categories/$categoryId': typeof FoodsCategoriesCategoryIdRoute
  '/learn/workout-science/$slug': typeof LearnWorkoutScienceSlugRoute
  '/learn/workout-science/glossary': typeof LearnWorkoutScienceGlossaryRoute
  '/learn/workout-science/methods': typeof LearnWorkoutScienceMethodsRoute
  '/nutrients/categories/$groupId': typeof NutrientsCategoriesGroupIdRoute
  '/nutrition/custom-foods/$customFoodId': typeof NutritionCustomFoodsCustomFoodIdRoute
  '/nutrition/day/$date': typeof NutritionDayDateRoute
  '/workout/history/$sessionId': typeof WorkoutHistorySessionIdRoute
  '/workout/session/$sessionId': typeof WorkoutSessionSessionIdRoute
  '/workout/summary/$sessionId': typeof WorkoutSummarySessionIdRoute
  '/diet-planning/plans/': typeof DietPlanningPlansIndexRoute
  '/nutrition/custom-foods/': typeof NutritionCustomFoodsIndexRoute
  '/workout/exercises/$exerciseId/history': typeof WorkoutExercisesExerciseIdHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cardio': typeof CardioRoute
  '/diet': typeof DietRoute
  '/eat': typeof EatRoute
  '/exercises': typeof ExercisesRoute
  '/foods': typeof FoodsRoute
  '/learn': typeof LearnRoute
  '/mobility': typeof MobilityRoute
  '/muscles': typeof MusclesRoute
  '/nutrients': typeof NutrientsRoute
  '/nutrition-log': typeof NutritionLogRoute
  '/programs': typeof ProgramsRoute
  '/progress': typeof ProgressRoute
  '/recipes': typeof RecipesRoute
  '/recovery': typeof RecoveryRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/supplements': typeof SupplementsRoute
  '/tools': typeof ToolsRoute
  '/track': typeof TrackRoute
  '/train': typeof TrainRoute
  '/training-science': typeof TrainingScienceRoute
  '/workout': typeof WorkoutRoute
  '/about/sources': typeof AboutSourcesRoute
  '/diet-planning/energy': typeof DietPlanningEnergyRoute
  '/diet-planning/goal': typeof DietPlanningGoalRoute
  '/diet-planning/macros': typeof DietPlanningMacrosRoute
  '/diet-planning/meal-distribution': typeof DietPlanningMealDistributionRoute
  '/diet-planning/methodology': typeof DietPlanningMethodologyRoute
  '/diet-planning/safety': typeof DietPlanningSafetyRoute
  '/exercises/$slug': typeof ExercisesSlugRoute
  '/foods/$slug': typeof FoodsSlugRoute
  '/foods/categories': typeof FoodsCategoriesRoute
  '/foods/compare': typeof FoodsCompareRoute
  '/foods/methodology': typeof FoodsMethodologyRoute
  '/foods/sources': typeof FoodsSourcesRoute
  '/learn/workout-science': typeof LearnWorkoutScienceRoute
  '/muscles/$slug': typeof MusclesSlugRoute
  '/nutrients/$slug': typeof NutrientsSlugRoute
  '/nutrients/compare': typeof NutrientsCompareRoute
  '/nutrients/frameworks': typeof NutrientsFrameworksRoute
  '/nutrients/glossary': typeof NutrientsGlossaryRoute
  '/nutrients/methodology': typeof NutrientsMethodologyRoute
  '/nutrients/reference-intakes': typeof NutrientsReferenceIntakesRoute
  '/nutrition/add': typeof NutritionAddRoute
  '/nutrition/day': typeof NutritionDayRouteWithChildren
  '/nutrition/history': typeof NutritionHistoryRoute
  '/nutrition/methodology': typeof NutritionMethodologyRoute
  '/nutrition/privacy': typeof NutritionPrivacyRoute
  '/nutrition/settings': typeof NutritionSettingsRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/programs/compare': typeof ProgramsCompareRoute
  '/programs/current': typeof ProgramsCurrentRoute
  '/programs/finder': typeof ProgramsFinderRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/workout/history': typeof WorkoutHistoryRoute
  '/workout/settings': typeof WorkoutSettingsRoute
  '/diet-planning': typeof DietPlanningIndexRoute
  '/nutrition': typeof NutritionIndexRoute
  '/diet-planning/plans/$planId': typeof DietPlanningPlansPlanIdRoute
  '/foods/categories/$categoryId': typeof FoodsCategoriesCategoryIdRoute
  '/learn/workout-science/$slug': typeof LearnWorkoutScienceSlugRoute
  '/learn/workout-science/glossary': typeof LearnWorkoutScienceGlossaryRoute
  '/learn/workout-science/methods': typeof LearnWorkoutScienceMethodsRoute
  '/nutrients/categories/$groupId': typeof NutrientsCategoriesGroupIdRoute
  '/nutrition/custom-foods/$customFoodId': typeof NutritionCustomFoodsCustomFoodIdRoute
  '/nutrition/day/$date': typeof NutritionDayDateRoute
  '/workout/history/$sessionId': typeof WorkoutHistorySessionIdRoute
  '/workout/session/$sessionId': typeof WorkoutSessionSessionIdRoute
  '/workout/summary/$sessionId': typeof WorkoutSummarySessionIdRoute
  '/diet-planning/plans': typeof DietPlanningPlansIndexRoute
  '/nutrition/custom-foods': typeof NutritionCustomFoodsIndexRoute
  '/workout/exercises/$exerciseId/history': typeof WorkoutExercisesExerciseIdHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cardio': typeof CardioRoute
  '/diet': typeof DietRoute
  '/diet-planning': typeof DietPlanningRouteWithChildren
  '/eat': typeof EatRoute
  '/exercises': typeof ExercisesRoute
  '/foods': typeof FoodsRoute
  '/learn': typeof LearnRoute
  '/mobility': typeof MobilityRoute
  '/muscles': typeof MusclesRoute
  '/nutrients': typeof NutrientsRoute
  '/nutrition': typeof NutritionRouteWithChildren
  '/nutrition-log': typeof NutritionLogRoute
  '/programs': typeof ProgramsRoute
  '/progress': typeof ProgressRoute
  '/recipes': typeof RecipesRoute
  '/recovery': typeof RecoveryRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/supplements': typeof SupplementsRoute
  '/tools': typeof ToolsRoute
  '/track': typeof TrackRoute
  '/train': typeof TrainRoute
  '/training-science': typeof TrainingScienceRoute
  '/workout': typeof WorkoutRoute
  '/about/sources': typeof AboutSourcesRoute
  '/diet-planning/energy': typeof DietPlanningEnergyRoute
  '/diet-planning/goal': typeof DietPlanningGoalRoute
  '/diet-planning/macros': typeof DietPlanningMacrosRoute
  '/diet-planning/meal-distribution': typeof DietPlanningMealDistributionRoute
  '/diet-planning/methodology': typeof DietPlanningMethodologyRoute
  '/diet-planning/plans': typeof DietPlanningPlansRouteWithChildren
  '/diet-planning/safety': typeof DietPlanningSafetyRoute
  '/exercises_/$slug': typeof ExercisesSlugRoute
  '/foods_/$slug': typeof FoodsSlugRoute
  '/foods_/categories': typeof FoodsCategoriesRoute
  '/foods_/compare': typeof FoodsCompareRoute
  '/foods_/methodology': typeof FoodsMethodologyRoute
  '/foods_/sources': typeof FoodsSourcesRoute
  '/learn_/workout-science': typeof LearnWorkoutScienceRoute
  '/muscles_/$slug': typeof MusclesSlugRoute
  '/nutrients_/$slug': typeof NutrientsSlugRoute
  '/nutrients_/compare': typeof NutrientsCompareRoute
  '/nutrients_/frameworks': typeof NutrientsFrameworksRoute
  '/nutrients_/glossary': typeof NutrientsGlossaryRoute
  '/nutrients_/methodology': typeof NutrientsMethodologyRoute
  '/nutrients_/reference-intakes': typeof NutrientsReferenceIntakesRoute
  '/nutrition/add': typeof NutritionAddRoute
  '/nutrition/custom-foods': typeof NutritionCustomFoodsRouteWithChildren
  '/nutrition/day': typeof NutritionDayRouteWithChildren
  '/nutrition/history': typeof NutritionHistoryRoute
  '/nutrition/methodology': typeof NutritionMethodologyRoute
  '/nutrition/privacy': typeof NutritionPrivacyRoute
  '/nutrition/settings': typeof NutritionSettingsRoute
  '/programs_/$slug': typeof ProgramsSlugRoute
  '/programs_/compare': typeof ProgramsCompareRoute
  '/programs_/current': typeof ProgramsCurrentRoute
  '/programs_/finder': typeof ProgramsFinderRoute
  '/recipes_/$slug': typeof RecipesSlugRoute
  '/workout_/history': typeof WorkoutHistoryRoute
  '/workout_/settings': typeof WorkoutSettingsRoute
  '/diet-planning/': typeof DietPlanningIndexRoute
  '/nutrition/': typeof NutritionIndexRoute
  '/diet-planning/plans/$planId': typeof DietPlanningPlansPlanIdRoute
  '/foods_/categories_/$categoryId': typeof FoodsCategoriesCategoryIdRoute
  '/learn_/workout-science_/$slug': typeof LearnWorkoutScienceSlugRoute
  '/learn_/workout-science_/glossary': typeof LearnWorkoutScienceGlossaryRoute
  '/learn_/workout-science_/methods': typeof LearnWorkoutScienceMethodsRoute
  '/nutrients_/categories_/$groupId': typeof NutrientsCategoriesGroupIdRoute
  '/nutrition/custom-foods/$customFoodId': typeof NutritionCustomFoodsCustomFoodIdRoute
  '/nutrition/day/$date': typeof NutritionDayDateRoute
  '/workout_/history_/$sessionId': typeof WorkoutHistorySessionIdRoute
  '/workout_/session/$sessionId': typeof WorkoutSessionSessionIdRoute
  '/workout_/summary/$sessionId': typeof WorkoutSummarySessionIdRoute
  '/diet-planning/plans/': typeof DietPlanningPlansIndexRoute
  '/nutrition/custom-foods/': typeof NutritionCustomFoodsIndexRoute
  '/workout_/exercises/$exerciseId/history': typeof WorkoutExercisesExerciseIdHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cardio'
    | '/diet'
    | '/diet-planning'
    | '/eat'
    | '/exercises'
    | '/foods'
    | '/learn'
    | '/mobility'
    | '/muscles'
    | '/nutrients'
    | '/nutrition'
    | '/nutrition-log'
    | '/programs'
    | '/progress'
    | '/recipes'
    | '/recovery'
    | '/saved'
    | '/settings'
    | '/supplements'
    | '/tools'
    | '/track'
    | '/train'
    | '/training-science'
    | '/workout'
    | '/about/sources'
    | '/diet-planning/energy'
    | '/diet-planning/goal'
    | '/diet-planning/macros'
    | '/diet-planning/meal-distribution'
    | '/diet-planning/methodology'
    | '/diet-planning/plans'
    | '/diet-planning/safety'
    | '/exercises/$slug'
    | '/foods/$slug'
    | '/foods/categories'
    | '/foods/compare'
    | '/foods/methodology'
    | '/foods/sources'
    | '/learn/workout-science'
    | '/muscles/$slug'
    | '/nutrients/$slug'
    | '/nutrients/compare'
    | '/nutrients/frameworks'
    | '/nutrients/glossary'
    | '/nutrients/methodology'
    | '/nutrients/reference-intakes'
    | '/nutrition/add'
    | '/nutrition/custom-foods'
    | '/nutrition/day'
    | '/nutrition/history'
    | '/nutrition/methodology'
    | '/nutrition/privacy'
    | '/nutrition/settings'
    | '/programs/$slug'
    | '/programs/compare'
    | '/programs/current'
    | '/programs/finder'
    | '/recipes/$slug'
    | '/workout/history'
    | '/workout/settings'
    | '/diet-planning/'
    | '/nutrition/'
    | '/diet-planning/plans/$planId'
    | '/foods/categories/$categoryId'
    | '/learn/workout-science/$slug'
    | '/learn/workout-science/glossary'
    | '/learn/workout-science/methods'
    | '/nutrients/categories/$groupId'
    | '/nutrition/custom-foods/$customFoodId'
    | '/nutrition/day/$date'
    | '/workout/history/$sessionId'
    | '/workout/session/$sessionId'
    | '/workout/summary/$sessionId'
    | '/diet-planning/plans/'
    | '/nutrition/custom-foods/'
    | '/workout/exercises/$exerciseId/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cardio'
    | '/diet'
    | '/eat'
    | '/exercises'
    | '/foods'
    | '/learn'
    | '/mobility'
    | '/muscles'
    | '/nutrients'
    | '/nutrition-log'
    | '/programs'
    | '/progress'
    | '/recipes'
    | '/recovery'
    | '/saved'
    | '/settings'
    | '/supplements'
    | '/tools'
    | '/track'
    | '/train'
    | '/training-science'
    | '/workout'
    | '/about/sources'
    | '/diet-planning/energy'
    | '/diet-planning/goal'
    | '/diet-planning/macros'
    | '/diet-planning/meal-distribution'
    | '/diet-planning/methodology'
    | '/diet-planning/safety'
    | '/exercises/$slug'
    | '/foods/$slug'
    | '/foods/categories'
    | '/foods/compare'
    | '/foods/methodology'
    | '/foods/sources'
    | '/learn/workout-science'
    | '/muscles/$slug'
    | '/nutrients/$slug'
    | '/nutrients/compare'
    | '/nutrients/frameworks'
    | '/nutrients/glossary'
    | '/nutrients/methodology'
    | '/nutrients/reference-intakes'
    | '/nutrition/add'
    | '/nutrition/day'
    | '/nutrition/history'
    | '/nutrition/methodology'
    | '/nutrition/privacy'
    | '/nutrition/settings'
    | '/programs/$slug'
    | '/programs/compare'
    | '/programs/current'
    | '/programs/finder'
    | '/recipes/$slug'
    | '/workout/history'
    | '/workout/settings'
    | '/diet-planning'
    | '/nutrition'
    | '/diet-planning/plans/$planId'
    | '/foods/categories/$categoryId'
    | '/learn/workout-science/$slug'
    | '/learn/workout-science/glossary'
    | '/learn/workout-science/methods'
    | '/nutrients/categories/$groupId'
    | '/nutrition/custom-foods/$customFoodId'
    | '/nutrition/day/$date'
    | '/workout/history/$sessionId'
    | '/workout/session/$sessionId'
    | '/workout/summary/$sessionId'
    | '/diet-planning/plans'
    | '/nutrition/custom-foods'
    | '/workout/exercises/$exerciseId/history'
  id:
    | '__root__'
    | '/'
    | '/cardio'
    | '/diet'
    | '/diet-planning'
    | '/eat'
    | '/exercises'
    | '/foods'
    | '/learn'
    | '/mobility'
    | '/muscles'
    | '/nutrients'
    | '/nutrition'
    | '/nutrition-log'
    | '/programs'
    | '/progress'
    | '/recipes'
    | '/recovery'
    | '/saved'
    | '/settings'
    | '/supplements'
    | '/tools'
    | '/track'
    | '/train'
    | '/training-science'
    | '/workout'
    | '/about/sources'
    | '/diet-planning/energy'
    | '/diet-planning/goal'
    | '/diet-planning/macros'
    | '/diet-planning/meal-distribution'
    | '/diet-planning/methodology'
    | '/diet-planning/plans'
    | '/diet-planning/safety'
    | '/exercises_/$slug'
    | '/foods_/$slug'
    | '/foods_/categories'
    | '/foods_/compare'
    | '/foods_/methodology'
    | '/foods_/sources'
    | '/learn_/workout-science'
    | '/muscles_/$slug'
    | '/nutrients_/$slug'
    | '/nutrients_/compare'
    | '/nutrients_/frameworks'
    | '/nutrients_/glossary'
    | '/nutrients_/methodology'
    | '/nutrients_/reference-intakes'
    | '/nutrition/add'
    | '/nutrition/custom-foods'
    | '/nutrition/day'
    | '/nutrition/history'
    | '/nutrition/methodology'
    | '/nutrition/privacy'
    | '/nutrition/settings'
    | '/programs_/$slug'
    | '/programs_/compare'
    | '/programs_/current'
    | '/programs_/finder'
    | '/recipes_/$slug'
    | '/workout_/history'
    | '/workout_/settings'
    | '/diet-planning/'
    | '/nutrition/'
    | '/diet-planning/plans/$planId'
    | '/foods_/categories_/$categoryId'
    | '/learn_/workout-science_/$slug'
    | '/learn_/workout-science_/glossary'
    | '/learn_/workout-science_/methods'
    | '/nutrients_/categories_/$groupId'
    | '/nutrition/custom-foods/$customFoodId'
    | '/nutrition/day/$date'
    | '/workout_/history_/$sessionId'
    | '/workout_/session/$sessionId'
    | '/workout_/summary/$sessionId'
    | '/diet-planning/plans/'
    | '/nutrition/custom-foods/'
    | '/workout_/exercises/$exerciseId/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardioRoute: typeof CardioRoute
  DietRoute: typeof DietRoute
  DietPlanningRoute: typeof DietPlanningRouteWithChildren
  EatRoute: typeof EatRoute
  ExercisesRoute: typeof ExercisesRoute
  FoodsRoute: typeof FoodsRoute
  LearnRoute: typeof LearnRoute
  MobilityRoute: typeof MobilityRoute
  MusclesRoute: typeof MusclesRoute
  NutrientsRoute: typeof NutrientsRoute
  NutritionRoute: typeof NutritionRouteWithChildren
  NutritionLogRoute: typeof NutritionLogRoute
  ProgramsRoute: typeof ProgramsRoute
  ProgressRoute: typeof ProgressRoute
  RecipesRoute: typeof RecipesRoute
  RecoveryRoute: typeof RecoveryRoute
  SavedRoute: typeof SavedRoute
  SettingsRoute: typeof SettingsRoute
  SupplementsRoute: typeof SupplementsRoute
  ToolsRoute: typeof ToolsRoute
  TrackRoute: typeof TrackRoute
  TrainRoute: typeof TrainRoute
  TrainingScienceRoute: typeof TrainingScienceRoute
  WorkoutRoute: typeof WorkoutRoute
  AboutSourcesRoute: typeof AboutSourcesRoute
  ExercisesSlugRoute: typeof ExercisesSlugRoute
  FoodsSlugRoute: typeof FoodsSlugRoute
  FoodsCategoriesRoute: typeof FoodsCategoriesRoute
  FoodsCompareRoute: typeof FoodsCompareRoute
  FoodsMethodologyRoute: typeof FoodsMethodologyRoute
  FoodsSourcesRoute: typeof FoodsSourcesRoute
  LearnWorkoutScienceRoute: typeof LearnWorkoutScienceRoute
  MusclesSlugRoute: typeof MusclesSlugRoute
  NutrientsSlugRoute: typeof NutrientsSlugRoute
  NutrientsCompareRoute: typeof NutrientsCompareRoute
  NutrientsFrameworksRoute: typeof NutrientsFrameworksRoute
  NutrientsGlossaryRoute: typeof NutrientsGlossaryRoute
  NutrientsMethodologyRoute: typeof NutrientsMethodologyRoute
  NutrientsReferenceIntakesRoute: typeof NutrientsReferenceIntakesRoute
  ProgramsSlugRoute: typeof ProgramsSlugRoute
  ProgramsCompareRoute: typeof ProgramsCompareRoute
  ProgramsCurrentRoute: typeof ProgramsCurrentRoute
  ProgramsFinderRoute: typeof ProgramsFinderRoute
  RecipesSlugRoute: typeof RecipesSlugRoute
  WorkoutHistoryRoute: typeof WorkoutHistoryRoute
  WorkoutSettingsRoute: typeof WorkoutSettingsRoute
  FoodsCategoriesCategoryIdRoute: typeof FoodsCategoriesCategoryIdRoute
  LearnWorkoutScienceSlugRoute: typeof LearnWorkoutScienceSlugRoute
  LearnWorkoutScienceGlossaryRoute: typeof LearnWorkoutScienceGlossaryRoute
  LearnWorkoutScienceMethodsRoute: typeof LearnWorkoutScienceMethodsRoute
  NutrientsCategoriesGroupIdRoute: typeof NutrientsCategoriesGroupIdRoute
  WorkoutHistorySessionIdRoute: typeof WorkoutHistorySessionIdRoute
  WorkoutSessionSessionIdRoute: typeof WorkoutSessionSessionIdRoute
  WorkoutSummarySessionIdRoute: typeof WorkoutSummarySessionIdRoute
  WorkoutExercisesExerciseIdHistoryRoute: typeof WorkoutExercisesExerciseIdHistoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cardio': {
      id: '/cardio'
      path: '/cardio'
      fullPath: '/cardio'
      preLoaderRoute: typeof CardioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diet': {
      id: '/diet'
      path: '/diet'
      fullPath: '/diet'
      preLoaderRoute: typeof DietRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diet-planning': {
      id: '/diet-planning'
      path: '/diet-planning'
      fullPath: '/diet-planning'
      preLoaderRoute: typeof DietPlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eat': {
      id: '/eat'
      path: '/eat'
      fullPath: '/eat'
      preLoaderRoute: typeof EatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises': {
      id: '/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods': {
      id: '/foods'
      path: '/foods'
      fullPath: '/foods'
      preLoaderRoute: typeof FoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobility': {
      id: '/mobility'
      path: '/mobility'
      fullPath: '/mobility'
      preLoaderRoute: typeof MobilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/muscles': {
      id: '/muscles'
      path: '/muscles'
      fullPath: '/muscles'
      preLoaderRoute: typeof MusclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrients': {
      id: '/nutrients'
      path: '/nutrients'
      fullPath: '/nutrients'
      preLoaderRoute: typeof NutrientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition-log': {
      id: '/nutrition-log'
      path: '/nutrition-log'
      fullPath: '/nutrition-log'
      preLoaderRoute: typeof NutritionLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplements': {
      id: '/supplements'
      path: '/supplements'
      fullPath: '/supplements'
      preLoaderRoute: typeof SupplementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train': {
      id: '/train'
      path: '/train'
      fullPath: '/train'
      preLoaderRoute: typeof TrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training-science': {
      id: '/training-science'
      path: '/training-science'
      fullPath: '/training-science'
      preLoaderRoute: typeof TrainingScienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout': {
      id: '/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof WorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/sources': {
      id: '/about/sources'
      path: '/about/sources'
      fullPath: '/about/sources'
      preLoaderRoute: typeof AboutSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diet-planning/': {
      id: '/diet-planning/'
      path: '/'
      fullPath: '/diet-planning/'
      preLoaderRoute: typeof DietPlanningIndexRouteImport
      parentRoute: typeof DietPlanningRoute
    }
    '/diet-planning/energy': {
      id: '/diet-planning/energy'
      path: '/energy'
      fullPath: '/diet-planning/energy'
      preLoaderRoute: typeof DietPlanningEnergyRouteImport
      parentRoute: typeof DietPlanningRoute
    }
    '/diet-planning/goal': {
      id: '/diet-planning/goal'
      path: '/goal'
      fullPath: '/diet-planning/goal'
      preLoaderRoute: typeof DietPlanningGoalRouteImport
      parentRoute: typeof DietPlanningRoute
    }
    '/diet-planning/macros': {
      id: '/diet-planning/macros'
      path: '/macros'
      fullPath: '/diet-planning/macros'
      preLoaderRoute: typeof DietPlanningMacrosRouteImport
      parentRoute: typeof DietPlanningRoute
    }
    '/diet-planning/meal-distribution': {
      id: '/diet-planning/meal-distribution'
      path: '/meal-distribution'
      fullPath: '/diet-planning/meal-distribution'
      preLoaderRoute: typeof DietPlanningMealDistributionRouteImport
      parentRoute: typeof DietPlanningRoute
    }
    '/diet-planning/methodology': {
      id: '/diet-planning/methodology'
      path: '/methodology'
      fullPath: '/diet-planning/methodology'
      preLoaderRoute: typeof DietPlanningMethodologyRouteImport
      parentRoute: typeof DietPlanningRoute
    }
    '/diet-planning/plans': {
      id: '/diet-planning/plans'
      path: '/plans'
      fullPath: '/diet-planning/plans'
      preLoaderRoute: typeof DietPlanningPlansRouteImport
      parentRoute: typeof DietPlanningRoute
    }
    '/diet-planning/safety': {
      id: '/diet-planning/safety'
      path: '/safety'
      fullPath: '/diet-planning/safety'
      preLoaderRoute: typeof DietPlanningSafetyRouteImport
      parentRoute: typeof DietPlanningRoute
    }
    '/exercises_/$slug': {
      id: '/exercises_/$slug'
      path: '/exercises/$slug'
      fullPath: '/exercises/$slug'
      preLoaderRoute: typeof ExercisesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods_/$slug': {
      id: '/foods_/$slug'
      path: '/foods/$slug'
      fullPath: '/foods/$slug'
      preLoaderRoute: typeof FoodsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods_/categories': {
      id: '/foods_/categories'
      path: '/foods/categories'
      fullPath: '/foods/categories'
      preLoaderRoute: typeof FoodsCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods_/compare': {
      id: '/foods_/compare'
      path: '/foods/compare'
      fullPath: '/foods/compare'
      preLoaderRoute: typeof FoodsCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods_/methodology': {
      id: '/foods_/methodology'
      path: '/foods/methodology'
      fullPath: '/foods/methodology'
      preLoaderRoute: typeof FoodsMethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods_/sources': {
      id: '/foods_/sources'
      path: '/foods/sources'
      fullPath: '/foods/sources'
      preLoaderRoute: typeof FoodsSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn_/workout-science': {
      id: '/learn_/workout-science'
      path: '/learn/workout-science'
      fullPath: '/learn/workout-science'
      preLoaderRoute: typeof LearnWorkoutScienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/muscles_/$slug': {
      id: '/muscles_/$slug'
      path: '/muscles/$slug'
      fullPath: '/muscles/$slug'
      preLoaderRoute: typeof MusclesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrients_/$slug': {
      id: '/nutrients_/$slug'
      path: '/nutrients/$slug'
      fullPath: '/nutrients/$slug'
      preLoaderRoute: typeof NutrientsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrients_/compare': {
      id: '/nutrients_/compare'
      path: '/nutrients/compare'
      fullPath: '/nutrients/compare'
      preLoaderRoute: typeof NutrientsCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrients_/frameworks': {
      id: '/nutrients_/frameworks'
      path: '/nutrients/frameworks'
      fullPath: '/nutrients/frameworks'
      preLoaderRoute: typeof NutrientsFrameworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrients_/glossary': {
      id: '/nutrients_/glossary'
      path: '/nutrients/glossary'
      fullPath: '/nutrients/glossary'
      preLoaderRoute: typeof NutrientsGlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrients_/methodology': {
      id: '/nutrients_/methodology'
      path: '/nutrients/methodology'
      fullPath: '/nutrients/methodology'
      preLoaderRoute: typeof NutrientsMethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrients_/reference-intakes': {
      id: '/nutrients_/reference-intakes'
      path: '/nutrients/reference-intakes'
      fullPath: '/nutrients/reference-intakes'
      preLoaderRoute: typeof NutrientsReferenceIntakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition/': {
      id: '/nutrition/'
      path: '/'
      fullPath: '/nutrition/'
      preLoaderRoute: typeof NutritionIndexRouteImport
      parentRoute: typeof NutritionRoute
    }
    '/nutrition/add': {
      id: '/nutrition/add'
      path: '/add'
      fullPath: '/nutrition/add'
      preLoaderRoute: typeof NutritionAddRouteImport
      parentRoute: typeof NutritionRoute
    }
    '/nutrition/custom-foods': {
      id: '/nutrition/custom-foods'
      path: '/custom-foods'
      fullPath: '/nutrition/custom-foods'
      preLoaderRoute: typeof NutritionCustomFoodsRouteImport
      parentRoute: typeof NutritionRoute
    }
    '/nutrition/day': {
      id: '/nutrition/day'
      path: '/day'
      fullPath: '/nutrition/day'
      preLoaderRoute: typeof NutritionDayRouteImport
      parentRoute: typeof NutritionRoute
    }
    '/nutrition/history': {
      id: '/nutrition/history'
      path: '/history'
      fullPath: '/nutrition/history'
      preLoaderRoute: typeof NutritionHistoryRouteImport
      parentRoute: typeof NutritionRoute
    }
    '/nutrition/methodology': {
      id: '/nutrition/methodology'
      path: '/methodology'
      fullPath: '/nutrition/methodology'
      preLoaderRoute: typeof NutritionMethodologyRouteImport
      parentRoute: typeof NutritionRoute
    }
    '/nutrition/privacy': {
      id: '/nutrition/privacy'
      path: '/privacy'
      fullPath: '/nutrition/privacy'
      preLoaderRoute: typeof NutritionPrivacyRouteImport
      parentRoute: typeof NutritionRoute
    }
    '/nutrition/settings': {
      id: '/nutrition/settings'
      path: '/settings'
      fullPath: '/nutrition/settings'
      preLoaderRoute: typeof NutritionSettingsRouteImport
      parentRoute: typeof NutritionRoute
    }
    '/programs_/$slug': {
      id: '/programs_/$slug'
      path: '/programs/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs_/compare': {
      id: '/programs_/compare'
      path: '/programs/compare'
      fullPath: '/programs/compare'
      preLoaderRoute: typeof ProgramsCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs_/current': {
      id: '/programs_/current'
      path: '/programs/current'
      fullPath: '/programs/current'
      preLoaderRoute: typeof ProgramsCurrentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs_/finder': {
      id: '/programs_/finder'
      path: '/programs/finder'
      fullPath: '/programs/finder'
      preLoaderRoute: typeof ProgramsFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes_/$slug': {
      id: '/recipes_/$slug'
      path: '/recipes/$slug'
      fullPath: '/recipes/$slug'
      preLoaderRoute: typeof RecipesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout_/history': {
      id: '/workout_/history'
      path: '/workout/history'
      fullPath: '/workout/history'
      preLoaderRoute: typeof WorkoutHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout_/settings': {
      id: '/workout_/settings'
      path: '/workout/settings'
      fullPath: '/workout/settings'
      preLoaderRoute: typeof WorkoutSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diet-planning/plans/': {
      id: '/diet-planning/plans/'
      path: '/'
      fullPath: '/diet-planning/plans/'
      preLoaderRoute: typeof DietPlanningPlansIndexRouteImport
      parentRoute: typeof DietPlanningPlansRoute
    }
    '/diet-planning/plans/$planId': {
      id: '/diet-planning/plans/$planId'
      path: '/$planId'
      fullPath: '/diet-planning/plans/$planId'
      preLoaderRoute: typeof DietPlanningPlansPlanIdRouteImport
      parentRoute: typeof DietPlanningPlansRoute
    }
    '/foods_/categories_/$categoryId': {
      id: '/foods_/categories_/$categoryId'
      path: '/foods/categories/$categoryId'
      fullPath: '/foods/categories/$categoryId'
      preLoaderRoute: typeof FoodsCategoriesCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn_/workout-science_/$slug': {
      id: '/learn_/workout-science_/$slug'
      path: '/learn/workout-science/$slug'
      fullPath: '/learn/workout-science/$slug'
      preLoaderRoute: typeof LearnWorkoutScienceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn_/workout-science_/glossary': {
      id: '/learn_/workout-science_/glossary'
      path: '/learn/workout-science/glossary'
      fullPath: '/learn/workout-science/glossary'
      preLoaderRoute: typeof LearnWorkoutScienceGlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn_/workout-science_/methods': {
      id: '/learn_/workout-science_/methods'
      path: '/learn/workout-science/methods'
      fullPath: '/learn/workout-science/methods'
      preLoaderRoute: typeof LearnWorkoutScienceMethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrients_/categories_/$groupId': {
      id: '/nutrients_/categories_/$groupId'
      path: '/nutrients/categories/$groupId'
      fullPath: '/nutrients/categories/$groupId'
      preLoaderRoute: typeof NutrientsCategoriesGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition/custom-foods/': {
      id: '/nutrition/custom-foods/'
      path: '/'
      fullPath: '/nutrition/custom-foods/'
      preLoaderRoute: typeof NutritionCustomFoodsIndexRouteImport
      parentRoute: typeof NutritionCustomFoodsRoute
    }
    '/nutrition/custom-foods/$customFoodId': {
      id: '/nutrition/custom-foods/$customFoodId'
      path: '/$customFoodId'
      fullPath: '/nutrition/custom-foods/$customFoodId'
      preLoaderRoute: typeof NutritionCustomFoodsCustomFoodIdRouteImport
      parentRoute: typeof NutritionCustomFoodsRoute
    }
    '/nutrition/day/$date': {
      id: '/nutrition/day/$date'
      path: '/$date'
      fullPath: '/nutrition/day/$date'
      preLoaderRoute: typeof NutritionDayDateRouteImport
      parentRoute: typeof NutritionDayRoute
    }
    '/workout_/history_/$sessionId': {
      id: '/workout_/history_/$sessionId'
      path: '/workout/history/$sessionId'
      fullPath: '/workout/history/$sessionId'
      preLoaderRoute: typeof WorkoutHistorySessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout_/session/$sessionId': {
      id: '/workout_/session/$sessionId'
      path: '/workout/session/$sessionId'
      fullPath: '/workout/session/$sessionId'
      preLoaderRoute: typeof WorkoutSessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout_/summary/$sessionId': {
      id: '/workout_/summary/$sessionId'
      path: '/workout/summary/$sessionId'
      fullPath: '/workout/summary/$sessionId'
      preLoaderRoute: typeof WorkoutSummarySessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout_/exercises/$exerciseId/history': {
      id: '/workout_/exercises/$exerciseId/history'
      path: '/workout/exercises/$exerciseId/history'
      fullPath: '/workout/exercises/$exerciseId/history'
      preLoaderRoute: typeof WorkoutExercisesExerciseIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DietPlanningPlansRouteChildren {
  DietPlanningPlansPlanIdRoute: typeof DietPlanningPlansPlanIdRoute
  DietPlanningPlansIndexRoute: typeof DietPlanningPlansIndexRoute
}

const DietPlanningPlansRouteChildren: DietPlanningPlansRouteChildren = {
  DietPlanningPlansPlanIdRoute: DietPlanningPlansPlanIdRoute,
  DietPlanningPlansIndexRoute: DietPlanningPlansIndexRoute,
}

const DietPlanningPlansRouteWithChildren =
  DietPlanningPlansRoute._addFileChildren(DietPlanningPlansRouteChildren)

interface DietPlanningRouteChildren {
  DietPlanningEnergyRoute: typeof DietPlanningEnergyRoute
  DietPlanningGoalRoute: typeof DietPlanningGoalRoute
  DietPlanningMacrosRoute: typeof DietPlanningMacrosRoute
  DietPlanningMealDistributionRoute: typeof DietPlanningMealDistributionRoute
  DietPlanningMethodologyRoute: typeof DietPlanningMethodologyRoute
  DietPlanningPlansRoute: typeof DietPlanningPlansRouteWithChildren
  DietPlanningSafetyRoute: typeof DietPlanningSafetyRoute
  DietPlanningIndexRoute: typeof DietPlanningIndexRoute
}

const DietPlanningRouteChildren: DietPlanningRouteChildren = {
  DietPlanningEnergyRoute: DietPlanningEnergyRoute,
  DietPlanningGoalRoute: DietPlanningGoalRoute,
  DietPlanningMacrosRoute: DietPlanningMacrosRoute,
  DietPlanningMealDistributionRoute: DietPlanningMealDistributionRoute,
  DietPlanningMethodologyRoute: DietPlanningMethodologyRoute,
  DietPlanningPlansRoute: DietPlanningPlansRouteWithChildren,
  DietPlanningSafetyRoute: DietPlanningSafetyRoute,
  DietPlanningIndexRoute: DietPlanningIndexRoute,
}

const DietPlanningRouteWithChildren = DietPlanningRoute._addFileChildren(
  DietPlanningRouteChildren,
)

interface NutritionCustomFoodsRouteChildren {
  NutritionCustomFoodsCustomFoodIdRoute: typeof NutritionCustomFoodsCustomFoodIdRoute
  NutritionCustomFoodsIndexRoute: typeof NutritionCustomFoodsIndexRoute
}

const NutritionCustomFoodsRouteChildren: NutritionCustomFoodsRouteChildren = {
  NutritionCustomFoodsCustomFoodIdRoute: NutritionCustomFoodsCustomFoodIdRoute,
  NutritionCustomFoodsIndexRoute: NutritionCustomFoodsIndexRoute,
}

const NutritionCustomFoodsRouteWithChildren =
  NutritionCustomFoodsRoute._addFileChildren(NutritionCustomFoodsRouteChildren)

interface NutritionDayRouteChildren {
  NutritionDayDateRoute: typeof NutritionDayDateRoute
}

const NutritionDayRouteChildren: NutritionDayRouteChildren = {
  NutritionDayDateRoute: NutritionDayDateRoute,
}

const NutritionDayRouteWithChildren = NutritionDayRoute._addFileChildren(
  NutritionDayRouteChildren,
)

interface NutritionRouteChildren {
  NutritionAddRoute: typeof NutritionAddRoute
  NutritionCustomFoodsRoute: typeof NutritionCustomFoodsRouteWithChildren
  NutritionDayRoute: typeof NutritionDayRouteWithChildren
  NutritionHistoryRoute: typeof NutritionHistoryRoute
  NutritionMethodologyRoute: typeof NutritionMethodologyRoute
  NutritionPrivacyRoute: typeof NutritionPrivacyRoute
  NutritionSettingsRoute: typeof NutritionSettingsRoute
  NutritionIndexRoute: typeof NutritionIndexRoute
}

const NutritionRouteChildren: NutritionRouteChildren = {
  NutritionAddRoute: NutritionAddRoute,
  NutritionCustomFoodsRoute: NutritionCustomFoodsRouteWithChildren,
  NutritionDayRoute: NutritionDayRouteWithChildren,
  NutritionHistoryRoute: NutritionHistoryRoute,
  NutritionMethodologyRoute: NutritionMethodologyRoute,
  NutritionPrivacyRoute: NutritionPrivacyRoute,
  NutritionSettingsRoute: NutritionSettingsRoute,
  NutritionIndexRoute: NutritionIndexRoute,
}

const NutritionRouteWithChildren = NutritionRoute._addFileChildren(
  NutritionRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardioRoute: CardioRoute,
  DietRoute: DietRoute,
  DietPlanningRoute: DietPlanningRouteWithChildren,
  EatRoute: EatRoute,
  ExercisesRoute: ExercisesRoute,
  FoodsRoute: FoodsRoute,
  LearnRoute: LearnRoute,
  MobilityRoute: MobilityRoute,
  MusclesRoute: MusclesRoute,
  NutrientsRoute: NutrientsRoute,
  NutritionRoute: NutritionRouteWithChildren,
  NutritionLogRoute: NutritionLogRoute,
  ProgramsRoute: ProgramsRoute,
  ProgressRoute: ProgressRoute,
  RecipesRoute: RecipesRoute,
  RecoveryRoute: RecoveryRoute,
  SavedRoute: SavedRoute,
  SettingsRoute: SettingsRoute,
  SupplementsRoute: SupplementsRoute,
  ToolsRoute: ToolsRoute,
  TrackRoute: TrackRoute,
  TrainRoute: TrainRoute,
  TrainingScienceRoute: TrainingScienceRoute,
  WorkoutRoute: WorkoutRoute,
  AboutSourcesRoute: AboutSourcesRoute,
  ExercisesSlugRoute: ExercisesSlugRoute,
  FoodsSlugRoute: FoodsSlugRoute,
  FoodsCategoriesRoute: FoodsCategoriesRoute,
  FoodsCompareRoute: FoodsCompareRoute,
  FoodsMethodologyRoute: FoodsMethodologyRoute,
  FoodsSourcesRoute: FoodsSourcesRoute,
  LearnWorkoutScienceRoute: LearnWorkoutScienceRoute,
  MusclesSlugRoute: MusclesSlugRoute,
  NutrientsSlugRoute: NutrientsSlugRoute,
  NutrientsCompareRoute: NutrientsCompareRoute,
  NutrientsFrameworksRoute: NutrientsFrameworksRoute,
  NutrientsGlossaryRoute: NutrientsGlossaryRoute,
  NutrientsMethodologyRoute: NutrientsMethodologyRoute,
  NutrientsReferenceIntakesRoute: NutrientsReferenceIntakesRoute,
  ProgramsSlugRoute: ProgramsSlugRoute,
  ProgramsCompareRoute: ProgramsCompareRoute,
  ProgramsCurrentRoute: ProgramsCurrentRoute,
  ProgramsFinderRoute: ProgramsFinderRoute,
  RecipesSlugRoute: RecipesSlugRoute,
  WorkoutHistoryRoute: WorkoutHistoryRoute,
  WorkoutSettingsRoute: WorkoutSettingsRoute,
  FoodsCategoriesCategoryIdRoute: FoodsCategoriesCategoryIdRoute,
  LearnWorkoutScienceSlugRoute: LearnWorkoutScienceSlugRoute,
  LearnWorkoutScienceGlossaryRoute: LearnWorkoutScienceGlossaryRoute,
  LearnWorkoutScienceMethodsRoute: LearnWorkoutScienceMethodsRoute,
  NutrientsCategoriesGroupIdRoute: NutrientsCategoriesGroupIdRoute,
  WorkoutHistorySessionIdRoute: WorkoutHistorySessionIdRoute,
  WorkoutSessionSessionIdRoute: WorkoutSessionSessionIdRoute,
  WorkoutSummarySessionIdRoute: WorkoutSummarySessionIdRoute,
  WorkoutExercisesExerciseIdHistoryRoute:
    WorkoutExercisesExerciseIdHistoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
